// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cfe7f02456486a1b "TaskFlow (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-47RE6EUY.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-HZSMZCXU.js";
import { routes } from "./chunks/chunk-UZZEI6KP.js";

// virtual:company-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/x9Xyvip0IOtQ2TqIadhW/a4fdSu11wy4em0yldoHy/h5qwnW8jC.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["Jn3yq4jWJ", "B2jgzndjK"];
var serializationHash = "framer-kfy8A";
var variantClassNames = {
	B2jgzndjK: "framer-v-ypkpdf",
	Jn3yq4jWJ: "framer-v-1hmft1x",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "Jn3yq4jWJ",
	Mobile: "B2jgzndjK",
};
var getProps = ({ height, id, image, text, title, width, ...props }) => {
	return {
		...props,
		ktt788aIk: image ??
			props.ktt788aIk ?? {
				src: "https://framerusercontent.com/images/G8LXbVm3TgWPtSR6JybaHu2lyXo.jpg?scale-down-to=2048",
				srcSet:
					"https://framerusercontent.com/images/G8LXbVm3TgWPtSR6JybaHu2lyXo.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/G8LXbVm3TgWPtSR6JybaHu2lyXo.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/G8LXbVm3TgWPtSR6JybaHu2lyXo.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/G8LXbVm3TgWPtSR6JybaHu2lyXo.jpg 2848w",
			},
		QwGfBX_xK: title ?? props.QwGfBX_xK ?? "Mission Statement",
		u3W1i7A2A:
			text ??
			props.u3W1i7A2A ??
			"To empower teams by providing intelligent tools that transform complex work management into seamless collaboration.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Jn3yq4jWJ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		QwGfBX_xK,
		u3W1i7A2A,
		ktt788aIk,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Jn3yq4jWJ",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1hmft1x",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Jn3yq4jWJ"}
						ref={ref ?? ref1}
						style={{
							backgroundColor:
								"var(--token-d0b7823d-e074-4a91-a0da-87403f8dd55f, rgb(249, 250, 251))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								B2jgzndjK: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1czuus9"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"czOvRwqok"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1vrzzpq"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Y2udHkWKw"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={QwGfBX_xK}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h2
										className={"framer-styles-preset-1owo7gc"}
										data-styles-preset={"IBoZbZL0y"}
									>
										{"Mission Statement"}
									</motion.h2>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-kv8npl"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"cgP820qRV"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={u3W1i7A2A}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1f6wsl4"}
										data-styles-preset={"VYWldt3Ia"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128)))",
										}}
									>
										{
											"To empower teams by providing intelligent tools that transform complex work management into seamless collaboration."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 16,
								),
								pixelHeight: 1696,
								pixelWidth: 2848,
								sizes: `max((${componentViewport?.width || "100vw"} - 64px) / 2, 1px)`,
								...toResponsiveImage(ktt788aIk),
							}}
							className={"framer-1vm8bem"}
							layoutDependency={layoutDependency}
							layoutId={"vQiJAnrZD"}
							style={{
								borderBottomLeftRadius: 12,
								borderBottomRightRadius: 12,
								borderTopLeftRadius: 12,
								borderTopRightRadius: 12,
							}}
							{...addPropertyOverrides(
								{
									B2jgzndjK: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													16 +
													(((componentViewport?.height || 526) - 32 - 566) / 2 +
														194 +
														32),
											),
											pixelHeight: 1696,
											pixelWidth: 2848,
											sizes: `calc(${componentViewport?.width || "100vw"} - 32px)`,
											...toResponsiveImage(ktt788aIk),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kfy8A.framer-sa1r1k, .framer-kfy8A .framer-sa1r1k { display: block; }",
	".framer-kfy8A.framer-1hmft1x { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 16px; position: relative; width: 1040px; }",
	".framer-kfy8A .framer-1czuus9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-kfy8A .framer-1vrzzpq, .framer-kfy8A .framer-kv8npl { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-kfy8A .framer-1vm8bem { flex: 1 0 0px; height: 340px; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-kfy8A.framer-1hmft1x, .framer-kfy8A .framer-1czuus9 { gap: 0px; } .framer-kfy8A.framer-1hmft1x > * { margin: 0px; margin-left: calc(32px / 2); margin-right: calc(32px / 2); } .framer-kfy8A.framer-1hmft1x > :first-child { margin-left: 0px; } .framer-kfy8A.framer-1hmft1x > :last-child { margin-right: 0px; } .framer-kfy8A .framer-1czuus9 > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-kfy8A .framer-1czuus9 > :first-child { margin-top: 0px; } .framer-kfy8A .framer-1czuus9 > :last-child { margin-bottom: 0px; } }",
	".framer-kfy8A.framer-v-ypkpdf.framer-1hmft1x { flex-direction: column; width: 844px; }",
	".framer-kfy8A.framer-v-ypkpdf .framer-1czuus9, .framer-kfy8A.framer-v-ypkpdf .framer-1vm8bem { flex: none; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-kfy8A.framer-v-ypkpdf.framer-1hmft1x { gap: 0px; } .framer-kfy8A.framer-v-ypkpdf.framer-1hmft1x > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-kfy8A.framer-v-ypkpdf.framer-1hmft1x > :first-child { margin-top: 0px; } .framer-kfy8A.framer-v-ypkpdf.framer-1hmft1x > :last-child { margin-bottom: 0px; } }",
	...css,
	...css2,
];
var Framerh5qwnW8jC = withCSS(Component, css3, "framer-kfy8A");
var stdin_default = Framerh5qwnW8jC;
Framerh5qwnW8jC.displayName = "Company Card";
Framerh5qwnW8jC.defaultProps = {
	height: 372,
	width: 1040,
};
addPropertyControls(Framerh5qwnW8jC, {
	variant: {
		options: ["Jn3yq4jWJ", "B2jgzndjK"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	QwGfBX_xK: {
		defaultValue: "Mission Statement",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	u3W1i7A2A: {
		defaultValue:
			"To empower teams by providing intelligent tools that transform complex work management into seamless collaboration.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	ktt788aIk: {
		__defaultAssetReference:
			"data:framer/asset-reference,G8LXbVm3TgWPtSR6JybaHu2lyXo.jpg?originalFilename=Qmctid9Vyqaw2t4sEYYFudBU6wTKQzyrYZhnLDJD8i6QxE.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	Framerh5qwnW8jC,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:company-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "B2jgzndjK",
	xl: "Jn3yq4jWJ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CompanyCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var company_card_default = ComponentWithRoot;
export { company_card_default as default };
