// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cfe7f02456486a1b "TaskFlow (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className as className7,
	className2 as className8,
	className3 as className9,
	css as css7,
	css2 as css8,
	css3 as css9,
	fonts as fonts7,
	fonts2 as fonts8,
	fonts3 as fonts9,
} from "./chunks/chunk-UVBREMLF.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-NP3XUHIS.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-EISZGXDF.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-E5FL3ZHE.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-47RE6EUY.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SHQ4TVQP.js";
import { className, css, fonts } from "./chunks/chunk-KO5WDYQX.js";
import { routes } from "./chunks/chunk-UZZEI6KP.js";

// virtual:faq-accordion
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/czzxPPXoWQuTmATQokbq/WyjkUFlqEtPJRQcaadJd/s87BNvK0R.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["f7kU6Hlxv", "uKTpiZhLT"];
var serializationHash = "framer-lR7oA";
var variantClassNames = {
	f7kU6Hlxv: "framer-v-1aqd3o",
	uKTpiZhLT: "framer-v-1akuay4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "uKTpiZhLT",
	Open: "f7kU6Hlxv",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		kMvcjJ13y: question ?? props.kMvcjJ13y ?? "How does TaskFlow pricing work?",
		P7lvV731g: answer ?? props.P7lvV731g ?? (
			<React.Fragment>
				<motion.p>
					{
						"TaskFlow offers three simple pricing tiers: Free, Pro ($10/user/month), and Business ($20/user/month). All paid plans are billed monthly or annually with a 20% discount for annual billing. You only pay for active team members, and you can upgrade, downgrade, or cancel at any time."
					}
				</motion.p>
			</React.Fragment>
		),
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "f7kU6Hlxv",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className10,
		layoutId,
		variant,
		kMvcjJ13y,
		P7lvV731g,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "f7kU6Hlxv",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1mv47cm = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("uKTpiZhLT");
	});
	const onTap51yzvv = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("f7kU6Hlxv");
	});
	const sharedStyleClassNames = [
		className2,
		className8,
		className3,
		className4,
		className9,
		className6,
		className,
		className5,
		className7,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "uKTpiZhLT") return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1aqd3o",
							className10,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"f7kU6Hlxv"}
						onTap={onTap1mv47cm}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(229, 231, 235, 0.3)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-d0b7823d-e074-4a91-a0da-87403f8dd55f, rgb(249, 250, 251))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
						variants={{
							uKTpiZhLT: {
								"--border-color": "rgb(229, 231, 235)",
							},
						}}
						{...addPropertyOverrides(
							{
								uKTpiZhLT: {
									"data-framer-name": "Close",
									onTap: onTap51yzvv,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1hbazh8"}
							data-framer-name={"Head"}
							layoutDependency={layoutDependency}
							layoutId={"LRj8tAvb7"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-14bdltn"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"zmm6oVlap"}
								style={{
									"--extracted-1lwpl3i":
										"var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={kMvcjJ13y}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h5
										className={"framer-styles-preset-q3obf1"}
										data-styles-preset={"O4i2T8vus"}
										style={{
											"--framer-text-color":
												"var(--extracted-1lwpl3i, var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39)))",
										}}
									>
										{"How does TaskFlow pricing work?"}
									</motion.h5>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-10he23z"}
								data-framer-name={"Opener"}
								layoutDependency={layoutDependency}
								layoutId={"MSc7nnrYO"}
							>
								<motion.div
									className={"framer-1tujom8"}
									data-framer-name={"Stroke"}
									layoutDependency={layoutDependency}
									layoutId={"vsL4Y86Cm"}
									style={{
										backgroundColor:
											"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
								/>
								<motion.div
									className={"framer-gsh0oz"}
									data-framer-name={"Stroke"}
									layoutDependency={layoutDependency}
									layoutId={"AB4aaX9Cc"}
									style={{
										backgroundColor:
											"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
										rotate: 0,
									}}
									variants={{
										uKTpiZhLT: {
											rotate: 90,
										},
									}}
								/>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-11lmhib"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"fo9wemER3"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								stylesPresetsClassNames={{
									a: "framer-styles-preset-1bgc7cg",
									code: "framer-styles-preset-5pv59m",
									h1: "framer-styles-preset-bzw91s",
									h2: "framer-styles-preset-1owo7gc",
									h3: "framer-styles-preset-1bfwuz9",
									h4: "framer-styles-preset-fcvc2w",
									h5: "framer-styles-preset-q3obf1",
									h6: "framer-styles-preset-1m23la7",
									p: "framer-styles-preset-15l7ucq",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								{P7lvV731g}
							</RichText>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css10 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lR7oA.framer-1f2qk5i, .framer-lR7oA .framer-1f2qk5i { display: block; }",
	".framer-lR7oA.framer-1aqd3o { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 16px; position: relative; width: 700px; will-change: var(--framer-will-change-override, transform); }",
	".framer-lR7oA .framer-1hbazh8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-lR7oA .framer-14bdltn { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-lR7oA .framer-10he23z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 24px; }",
	".framer-lR7oA .framer-1tujom8, .framer-lR7oA .framer-gsh0oz { flex: none; height: 2px; left: calc(50.00000000000002% - 18px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 18px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-lR7oA .framer-11lmhib { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lR7oA.framer-1aqd3o, .framer-lR7oA .framer-1hbazh8, .framer-lR7oA .framer-10he23z { gap: 0px; } .framer-lR7oA.framer-1aqd3o > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-lR7oA.framer-1aqd3o > :first-child, .framer-lR7oA .framer-10he23z > :first-child { margin-top: 0px; } .framer-lR7oA.framer-1aqd3o > :last-child, .framer-lR7oA .framer-10he23z > :last-child { margin-bottom: 0px; } .framer-lR7oA .framer-1hbazh8 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-lR7oA .framer-1hbazh8 > :first-child { margin-left: 0px; } .framer-lR7oA .framer-1hbazh8 > :last-child { margin-right: 0px; } .framer-lR7oA .framer-10he23z > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	".framer-lR7oA.framer-v-1akuay4 .framer-1hbazh8 { order: 0; }",
	...css2,
	...css8,
	...css3,
	...css4,
	...css9,
	...css6,
	...css,
	...css5,
	...css7,
	'.framer-lR7oA[data-border="true"]::after, .framer-lR7oA [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framers87BNvK0R = withCSS(Component, css10, "framer-lR7oA");
var stdin_default = Framers87BNvK0R;
Framers87BNvK0R.displayName = "FAQ Accordion";
Framers87BNvK0R.defaultProps = {
	height: 160,
	width: 700,
};
addPropertyControls(Framers87BNvK0R, {
	variant: {
		options: ["f7kU6Hlxv", "uKTpiZhLT"],
		optionTitles: ["Open", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	kMvcjJ13y: {
		defaultValue: "How does TaskFlow pricing work?",
		displayTextArea: false,
		title: "Question",
		type: ControlType.String,
	},
	P7lvV731g: {
		defaultValue:
			"<p>TaskFlow offers three simple pricing tiers: Free, Pro ($10/user/month), and Business ($20/user/month). All paid plans are billed monthly or annually with a 20% discount for annual billing. You only pay for active team members, and you can upgrade, downgrade, or cancel at any time.</p>",
		title: "Answer",
		type: ControlType.RichText,
	},
});
addFonts(
	Framers87BNvK0R,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts9),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts7),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "uKTpiZhLT",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqAccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var faq_accordion_default = ComponentWithRoot;
export { faq_accordion_default as default };
