// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cfe7f02456486a1b "TaskFlow (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className as className8,
	className2 as className9,
	className3 as className10,
	css as css8,
	css2 as css9,
	css3 as css10,
	fonts as fonts8,
	fonts2 as fonts9,
	fonts3 as fonts10,
} from "./chunks/chunk-UVBREMLF.js";
import {
	className as className7,
	css as css7,
	fonts as fonts7,
} from "./chunks/chunk-NP3XUHIS.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-EISZGXDF.js";
import { stdin_default } from "./chunks/chunk-XOCSB6QP.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-E5FL3ZHE.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-47RE6EUY.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-HZSMZCXU.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SHQ4TVQP.js";
import "./chunks/chunk-U5LHETZW.js";
import { className, css, fonts } from "./chunks/chunk-KO5WDYQX.js";
import { routes } from "./chunks/chunk-UZZEI6KP.js";

// virtual:faq
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/y7HSFq1gTJagu9CDx7Hd/EUxzqjCKMt7vqBdlkO3E/YJQuDHbBq.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/9sWwZOzUjghLSSmuLzWX/pQ7XRezcAhiTPGjvJV75/s87BNvK0R.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["f7kU6Hlxv", "uKTpiZhLT"];
var serializationHash = "framer-lR7oA";
var variantClassNames = {
	f7kU6Hlxv: "framer-v-1aqd3o",
	uKTpiZhLT: "framer-v-1akuay4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "uKTpiZhLT",
	Open: "f7kU6Hlxv",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		kMvcjJ13y: question ?? props.kMvcjJ13y ?? "Hogyan működik az előfizetés?",
		P7lvV731g: answer ?? props.P7lvV731g ?? (
			<React.Fragment>
				<motion.p>
					{
						"A DMA MasterClass havi előfizetéses modellben működik. Egyéni felhasználóként vagy céges csapattal (max. 10 fő) is előfizethetsz. Az előfizetés bármikor lemondható, és a teljes tartalomkönyvtárhoz azonnal hozzáférsz."
					}
				</motion.p>
			</React.Fragment>
		),
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "f7kU6Hlxv",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className11,
		layoutId,
		variant,
		kMvcjJ13y,
		P7lvV731g,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "f7kU6Hlxv",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1mv47cm = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("uKTpiZhLT");
	});
	const onTap51yzvv = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("f7kU6Hlxv");
	});
	const sharedStyleClassNames = [
		className2,
		className9,
		className3,
		className5,
		className10,
		className7,
		className,
		className6,
		className8,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "uKTpiZhLT") return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1aqd3o",
							className11,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"f7kU6Hlxv"}
						onTap={onTap1mv47cm}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(229, 231, 235, 0.3)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-d0b7823d-e074-4a91-a0da-87403f8dd55f, rgb(249, 250, 251))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
						variants={{
							uKTpiZhLT: {
								"--border-color": "rgb(229, 231, 235)",
							},
						}}
						{...addPropertyOverrides(
							{
								uKTpiZhLT: {
									"data-framer-name": "Close",
									onTap: onTap51yzvv,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1hbazh8"}
							data-framer-name={"Head"}
							layoutDependency={layoutDependency}
							layoutId={"LRj8tAvb7"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-14bdltn"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"zmm6oVlap"}
								style={{
									"--extracted-1lwpl3i":
										"var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={kMvcjJ13y}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h5
										className={"framer-styles-preset-q3obf1"}
										data-styles-preset={"O4i2T8vus"}
										style={{
											"--framer-text-color":
												"var(--extracted-1lwpl3i, var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39)))",
										}}
									>
										{"Hogyan működik az előfizetés?"}
									</motion.h5>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-10he23z"}
								data-framer-name={"Opener"}
								layoutDependency={layoutDependency}
								layoutId={"MSc7nnrYO"}
							>
								<motion.div
									className={"framer-1tujom8"}
									data-framer-name={"Stroke"}
									layoutDependency={layoutDependency}
									layoutId={"vsL4Y86Cm"}
									style={{
										backgroundColor:
											"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
								/>
								<motion.div
									className={"framer-gsh0oz"}
									data-framer-name={"Stroke"}
									layoutDependency={layoutDependency}
									layoutId={"AB4aaX9Cc"}
									style={{
										backgroundColor:
											"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
										rotate: 0,
									}}
									variants={{
										uKTpiZhLT: {
											rotate: 90,
										},
									}}
								/>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-11lmhib"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"fo9wemER3"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								stylesPresetsClassNames={{
									a: "framer-styles-preset-1bgc7cg",
									code: "framer-styles-preset-5pv59m",
									h1: "framer-styles-preset-bzw91s",
									h2: "framer-styles-preset-1owo7gc",
									h3: "framer-styles-preset-1bfwuz9",
									h4: "framer-styles-preset-fcvc2w",
									h5: "framer-styles-preset-q3obf1",
									h6: "framer-styles-preset-1m23la7",
									p: "framer-styles-preset-15l7ucq",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								{P7lvV731g}
							</RichText>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css11 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lR7oA.framer-1f2qk5i, .framer-lR7oA .framer-1f2qk5i { display: block; }",
	".framer-lR7oA.framer-1aqd3o { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 16px; position: relative; width: 700px; will-change: var(--framer-will-change-override, transform); }",
	".framer-lR7oA .framer-1hbazh8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-lR7oA .framer-14bdltn { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-lR7oA .framer-10he23z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 24px; }",
	".framer-lR7oA .framer-1tujom8, .framer-lR7oA .framer-gsh0oz { flex: none; height: 2px; left: calc(50.00000000000002% - 18px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 18px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-lR7oA .framer-11lmhib { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lR7oA.framer-1aqd3o, .framer-lR7oA .framer-1hbazh8, .framer-lR7oA .framer-10he23z { gap: 0px; } .framer-lR7oA.framer-1aqd3o > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-lR7oA.framer-1aqd3o > :first-child, .framer-lR7oA .framer-10he23z > :first-child { margin-top: 0px; } .framer-lR7oA.framer-1aqd3o > :last-child, .framer-lR7oA .framer-10he23z > :last-child { margin-bottom: 0px; } .framer-lR7oA .framer-1hbazh8 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-lR7oA .framer-1hbazh8 > :first-child { margin-left: 0px; } .framer-lR7oA .framer-1hbazh8 > :last-child { margin-right: 0px; } .framer-lR7oA .framer-10he23z > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	".framer-lR7oA.framer-v-1akuay4 .framer-1hbazh8 { order: 0; }",
	...css2,
	...css9,
	...css3,
	...css5,
	...css10,
	...css7,
	...css,
	...css6,
	...css8,
	'.framer-lR7oA[data-border="true"]::after, .framer-lR7oA [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framers87BNvK0R = withCSS(Component, css11, "framer-lR7oA");
var stdin_default2 = Framers87BNvK0R;
Framers87BNvK0R.displayName = "FAQ Accordion";
Framers87BNvK0R.defaultProps = {
	height: 160,
	width: 700,
};
addPropertyControls(Framers87BNvK0R, {
	variant: {
		options: ["f7kU6Hlxv", "uKTpiZhLT"],
		optionTitles: ["Open", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	kMvcjJ13y: {
		defaultValue: "Hogyan működik az előfizetés?",
		displayTextArea: false,
		title: "Question",
		type: ControlType.String,
	},
	P7lvV731g: {
		defaultValue:
			"<p>A DMA MasterClass havi előfizetéses modellben működik. Egyéni felhasználóként vagy céges csapattal (max. 10 fő) is előfizethetsz. Az előfizetés bármikor lemondható, és a teljes tartalomkönyvtárhoz azonnal hozzáférsz.</p>",
		title: "Answer",
		type: ControlType.RichText,
	},
});
addFonts(
	Framers87BNvK0R,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts9),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts10),
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts8),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/y7HSFq1gTJagu9CDx7Hd/EUxzqjCKMt7vqBdlkO3E/YJQuDHbBq.js
var BadgeMiniFonts = getFonts(stdin_default);
var FAQAccordionFonts = getFonts(stdin_default2);
var cycleOrder2 = ["lZoNGwaTp", "DKQgzH6bM", "QeRFHK1V1"];
var serializationHash2 = "framer-nzueI";
var variantClassNames2 = {
	DKQgzH6bM: "framer-v-1ygobt7",
	lZoNGwaTp: "framer-v-1997fau",
	QeRFHK1V1: "framer-v-1uygef1",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "lZoNGwaTp",
	Phone: "QeRFHK1V1",
	Tablet: "DKQgzH6bM",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "lZoNGwaTp",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className11,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "lZoNGwaTp",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className3, className4];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1997fau",
							className11,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"lZoNGwaTp"}
						ref={ref ?? ref1}
						style={{
							backgroundColor: "rgb(249, 250, 251)",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								DKQgzH6bM: {
									"data-framer-name": "Tablet",
								},
								QeRFHK1V1: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-njzbmf"}
							data-framer-name={"Padding"}
							layoutDependency={layoutDependency}
							layoutId={"E9a9eOkdH"}
						>
							<motion2.div
								className={"framer-qcmuux"}
								data-framer-name={"Head Content"}
								layoutDependency={layoutDependency}
								layoutId={"jU5KhRqTa"}
							>
								<ComponentViewportProvider
									height={28}
									y={
										(componentViewport?.y || 0) +
										(80 +
											((componentViewport?.height || 686) - 160 - 1142) / 2) +
										0 +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											QeRFHK1V1: {
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 200) - 120 - 1162) /
															2) +
													0 +
													0 +
													20 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-12qdyeu-container"}
										layoutDependency={layoutDependency}
										layoutId={"T4vGgPULx-container"}
									>
										{_jsx2(stdin_default, {
											gQqOpdg6s: "GYIK",
											height: "100%",
											id: "T4vGgPULx",
											layoutId: "T4vGgPULx",
											width: "100%",
										})}
									</motion2.div>
								</ComponentViewportProvider>
								<motion2.div
									className={"framer-1dy57a1"}
									data-framer-name={"Head Text"}
									layoutDependency={layoutDependency}
									layoutId={"tGkuUdueu"}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-nu9bzn"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"az35IO5Bn"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h2
												className={"framer-styles-preset-1owo7gc"}
												data-styles-preset={"IBoZbZL0y"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39)))",
												}}
											>
												{"Gyakran ismételt kérdések"}
											</motion2.h2>
										</React2.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-85p5tj"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"t_X_4dzQx"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												className={"framer-styles-preset-1f6wsl4"}
												data-styles-preset={"VYWldt3Ia"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128)))",
												}}
											>
												{"Mielőtt elkezded"}
											</motion2.p>
										</React2.Fragment>
									</RichText2>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-1pvwkvc"}
								data-framer-name={"FAQ Group"}
								layoutDependency={layoutDependency}
								layoutId={"O66KlPOze"}
							>
								<ComponentViewportProvider
									height={160}
									width={`min(min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px), 700px)`}
									y={
										(componentViewport?.y || 0) +
										(80 +
											((componentViewport?.height || 686) - 160 - 1142) / 2) +
										0 +
										310 +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											DKQgzH6bM: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px), 700px)`,
											},
											QeRFHK1V1: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px), 700px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 200) - 120 - 1162) /
															2) +
													0 +
													330 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-lywa5c-container"}
										layoutDependency={layoutDependency}
										layoutId={"VKvaVYngY-container"}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "VKvaVYngY",
											kMvcjJ13y: "Miben más a DMA, mint a Coursera vagy az Udemy?",
											layoutId: "VKvaVYngY",
											P7lvV731g: (
												<React2.Fragment>
													<p>
														{
															"A DMA nem általános online tartalmakat kínál. Minden anyagunk a Vállalati Térkép módszertanra épül – egy 20 éve fejlesztett, 50+ cégnél bizonyított rendszerre. Nem inspirációt kapsz, hanem konkrét keretrendszereket, amiket azonnal alkalmazhatsz."
														}
													</p>
												</React2.Fragment>
											),
											style: {
												width: "100%",
											},
											variant: "uKTpiZhLT",
											width: "100%",
										})}
									</motion2.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={160}
									width={`min(min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px), 700px)`}
									y={
										(componentViewport?.y || 0) +
										(80 +
											((componentViewport?.height || 686) - 160 - 1142) / 2) +
										0 +
										310 +
										0 +
										168
									}
									{...addPropertyOverrides2(
										{
											DKQgzH6bM: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px), 700px)`,
											},
											QeRFHK1V1: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px), 700px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 200) - 120 - 1162) /
															2) +
													0 +
													330 +
													0 +
													168,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-lzk62f-container"}
										layoutDependency={layoutDependency}
										layoutId={"dLRgpXSNA-container"}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "dLRgpXSNA",
											kMvcjJ13y: "Tényleg ingyen kipróbálhatom 7 napig?",
											layoutId: "dLRgpXSNA",
											P7lvV731g: (
												<React2.Fragment>
													<p>
														{
															"Igen, teljes hozzáféréssel. Nem kell bankkártya, nincs automatikus terhelés. Ha nem tetszik, egyszerűen nem csinálsz semmit – nem fogunk zaklatni."
														}
													</p>
												</React2.Fragment>
											),
											style: {
												width: "100%",
											},
											variant: "uKTpiZhLT",
											width: "100%",
										})}
									</motion2.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={160}
									width={`min(min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px), 700px)`}
									y={
										(componentViewport?.y || 0) +
										(80 +
											((componentViewport?.height || 686) - 160 - 1142) / 2) +
										0 +
										310 +
										0 +
										336
									}
									{...addPropertyOverrides2(
										{
											DKQgzH6bM: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px), 700px)`,
											},
											QeRFHK1V1: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px), 700px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 200) - 120 - 1162) /
															2) +
													0 +
													330 +
													0 +
													336,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-hph133-container"}
										layoutDependency={layoutDependency}
										layoutId={"bLE1jT0Ml-container"}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "bLE1jT0Ml",
											kMvcjJ13y: "Mennyi időt igényel?",
											layoutId: "bLE1jT0Ml",
											P7lvV731g: (
												<React2.Fragment>
													<p>
														{
															"Te döntöd el. Egy webinár 90 perc. Egy akadémia 10-20 szekció, amit a saját tempódban végezhetsz. A podcastokat útközben hallgathatod. Nincs határidő, nincs nyomás."
														}
													</p>
												</React2.Fragment>
											),
											style: {
												width: "100%",
											},
											variant: "uKTpiZhLT",
											width: "100%",
										})}
									</motion2.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={160}
									width={`min(min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px), 700px)`}
									y={
										(componentViewport?.y || 0) +
										(80 +
											((componentViewport?.height || 686) - 160 - 1142) / 2) +
										0 +
										310 +
										0 +
										504
									}
									{...addPropertyOverrides2(
										{
											DKQgzH6bM: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px), 700px)`,
											},
											QeRFHK1V1: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px), 700px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 200) - 120 - 1162) /
															2) +
													0 +
													330 +
													0 +
													504,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-idgles-container"}
										layoutDependency={layoutDependency}
										layoutId={"LPTMtyJjT-container"}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "LPTMtyJjT",
											kMvcjJ13y: "Egyénként és cégként is használhatom?",
											layoutId: "LPTMtyJjT",
											P7lvV731g: (
												<React2.Fragment>
													<p>
														{
															"Igen. Egyéni előfizetéssel a saját fejlődésedre koncentrálhatsz. Céges előfizetéssel a teljes csapatod hozzáférést kap, te pedig látod a haladásukat és az eredményeket."
														}
													</p>
												</React2.Fragment>
											),
											style: {
												width: "100%",
											},
											variant: "uKTpiZhLT",
											width: "100%",
										})}
									</motion2.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={160}
									width={`min(min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px), 700px)`}
									y={
										(componentViewport?.y || 0) +
										(80 +
											((componentViewport?.height || 686) - 160 - 1142) / 2) +
										0 +
										310 +
										0 +
										672
									}
									{...addPropertyOverrides2(
										{
											DKQgzH6bM: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px), 700px)`,
											},
											QeRFHK1V1: {
												width: `min(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px), 700px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 200) - 120 - 1162) /
															2) +
													0 +
													330 +
													0 +
													672,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-1hx21q1-container"}
										layoutDependency={layoutDependency}
										layoutId={"AiPCLREZo-container"}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "AiPCLREZo",
											kMvcjJ13y: "Mi van, ha nem tetszik?",
											layoutId: "AiPCLREZo",
											P7lvV731g: (
												<React2.Fragment>
													<p>
														{
															"A 7 napos próba után bármikor lemondhatsz egyetlen kattintással. Nincs hosszú távú elköteleződés, nincs rejtett költség. Ha úgy érzed, nem neked való – nincs harag."
														}
													</p>
												</React2.Fragment>
											),
											style: {
												width: "100%",
											},
											variant: "uKTpiZhLT",
											width: "100%",
										})}
									</motion2.div>
								</ComponentViewportProvider>
							</motion2.div>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css12 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-nzueI.framer-1t092g5, .framer-nzueI .framer-1t092g5 { display: block; }",
	".framer-nzueI.framer-1997fau { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 80px; position: relative; width: 1200px; }",
	".framer-nzueI .framer-njzbmf { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-nzueI .framer-qcmuux { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 640px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-nzueI .framer-12qdyeu-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-nzueI .framer-1dy57a1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-nzueI .framer-nu9bzn, .framer-nzueI .framer-85p5tj { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-nzueI .framer-1pvwkvc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; max-width: 700px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-nzueI .framer-lywa5c-container, .framer-nzueI .framer-lzk62f-container, .framer-nzueI .framer-hph133-container, .framer-nzueI .framer-idgles-container, .framer-nzueI .framer-1hx21q1-container { flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-nzueI.framer-1997fau, .framer-nzueI .framer-njzbmf, .framer-nzueI .framer-qcmuux, .framer-nzueI .framer-1dy57a1, .framer-nzueI .framer-1pvwkvc { gap: 0px; } .framer-nzueI.framer-1997fau > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-nzueI.framer-1997fau > :first-child { margin-left: 0px; } .framer-nzueI.framer-1997fau > :last-child { margin-right: 0px; } .framer-nzueI .framer-njzbmf > * { margin: 0px; margin-bottom: calc(80px / 2); margin-top: calc(80px / 2); } .framer-nzueI .framer-njzbmf > :first-child, .framer-nzueI .framer-qcmuux > :first-child, .framer-nzueI .framer-1dy57a1 > :first-child, .framer-nzueI .framer-1pvwkvc > :first-child { margin-top: 0px; } .framer-nzueI .framer-njzbmf > :last-child, .framer-nzueI .framer-qcmuux > :last-child, .framer-nzueI .framer-1dy57a1 > :last-child, .framer-nzueI .framer-1pvwkvc > :last-child { margin-bottom: 0px; } .framer-nzueI .framer-qcmuux > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-nzueI .framer-1dy57a1 > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-nzueI .framer-1pvwkvc > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } }",
	".framer-nzueI.framer-v-1ygobt7.framer-1997fau { padding: 80px 32px 80px 32px; width: 810px; }",
	".framer-nzueI.framer-v-1uygef1.framer-1997fau { padding: 60px 20px 60px 20px; width: 390px; }",
	".framer-nzueI.framer-v-1uygef1 .framer-njzbmf { gap: 60px; }",
	".framer-nzueI.framer-v-1uygef1 .framer-qcmuux { order: 0; padding: 20px; }",
	".framer-nzueI.framer-v-1uygef1 .framer-1pvwkvc { order: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-nzueI.framer-v-1uygef1 .framer-njzbmf { gap: 0px; } .framer-nzueI.framer-v-1uygef1 .framer-njzbmf > * { margin: 0px; margin-bottom: calc(60px / 2); margin-top: calc(60px / 2); } .framer-nzueI.framer-v-1uygef1 .framer-njzbmf > :first-child { margin-top: 0px; } .framer-nzueI.framer-v-1uygef1 .framer-njzbmf > :last-child { margin-bottom: 0px; } }",
	...css3,
	...css4,
];
var FramerYJQuDHbBq = withCSS2(Component2, css12, "framer-nzueI");
var stdin_default3 = FramerYJQuDHbBq;
FramerYJQuDHbBq.displayName = "FAQ";
FramerYJQuDHbBq.defaultProps = {
	height: 686,
	width: 1200,
};
addPropertyControls2(FramerYJQuDHbBq, {
	variant: {
		options: ["lZoNGwaTp", "DKQgzH6bM", "QeRFHK1V1"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerYJQuDHbBq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BadgeMiniFonts,
		...FAQAccordionFonts,
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "QeRFHK1V1",
	md: "DKQgzH6bM",
	xl: "lZoNGwaTp",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var faq_default = ComponentWithRoot;
export { faq_default as default };
