// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0b0481a8406af03e "Dreelio - Framer Template (copy)", do not edit manually */
"use client";

// virtual:hero
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/MXTbrnyZ1ea7UCQ9BkOR/ffjxQpjFhVhAOLjcIInh/B0Ga6wrMD.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	ComponentViewportProvider,
	cx as cx3,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	ResolveLinks,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useRouter,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
	withFX as withFX2,
	withOptimizedAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/mrpgdPIvPmnadTU0QfuN/Bf1kjTKnOktn3DoiMLhs/DrbjvzOzc.js
import { fontStore } from "unframer";
fontStore.loadFonts(["BI;Open Runde/Semibold/v0"]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/hG3wmGmFwadB6X5XPVXkMlmLr8o.woff2",
				weight: "600",
			},
		],
	},
];
var css = [
	'.framer-hd8Pm .framer-styles-preset-klyx7p:not(.rich-text-wrapper), .framer-hd8Pm .framer-styles-preset-klyx7p.rich-text-wrapper h1 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 76px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-hd8Pm .framer-styles-preset-klyx7p:not(.rich-text-wrapper), .framer-hd8Pm .framer-styles-preset-klyx7p.rich-text-wrapper h1 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 58px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-hd8Pm .framer-styles-preset-klyx7p:not(.rich-text-wrapper), .framer-hd8Pm .framer-styles-preset-klyx7p.rich-text-wrapper h1 { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, #1a1615); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-hd8Pm";

// /:https://framerusercontent.com/modules/22joqeQYw10gjSpK1lJA/O9eUy47RggGpuxigxW2x/KNLSIQOAc.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts(["BI;Open Runde/Regular/v0", "BI;Open Runde/Semibold/v0"]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/3exmuO07FP19gMM08TQrpXl3BGQ.woff2",
				weight: "400",
			},
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/hG3wmGmFwadB6X5XPVXkMlmLr8o.woff2",
				weight: "600",
			},
		],
	},
];
var css2 = [
	'.framer-HTMon .framer-styles-preset-w183k8:not(.rich-text-wrapper), .framer-HTMon .framer-styles-preset-w183k8.rich-text-wrapper p { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-family-bold: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 600; --framer-letter-spacing: 0em; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-b11f95a4-bdbc-426c-b836-3f8af50cb50f, #453f3d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-HTMon .framer-styles-preset-w183k8:not(.rich-text-wrapper), .framer-HTMon .framer-styles-preset-w183k8.rich-text-wrapper p { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-family-bold: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 600; --framer-letter-spacing: 0em; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-b11f95a4-bdbc-426c-b836-3f8af50cb50f, #453f3d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-HTMon .framer-styles-preset-w183k8:not(.rich-text-wrapper), .framer-HTMon .framer-styles-preset-w183k8.rich-text-wrapper p { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-family-bold: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 600; --framer-letter-spacing: 0em; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-b11f95a4-bdbc-426c-b836-3f8af50cb50f, #453f3d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-HTMon";

// /:https://framerusercontent.com/modules/PLNlfve6zVAt0RoX8I8G/nZfC9nafzBz1h5I48yc4/FJMj3QX_F.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var serializationHash = "framer-8Qzrr";
var variantClassNames = {
	uPrggLWN7: "framer-v-vci1j0",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "uPrggLWN7",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<ImageWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__spring={{
							bounce: 0,
							damping: 100,
							delay: 0,
							duration: 6.3,
							durationBasedSpring: false,
							ease: [0.44, 0, 0.56, 1],
							mass: 1,
							stiffness: 400,
							type: "spring",
						}}
						__framer__styleTransformEffectEnabled={true}
						__framer__transformTargets={[
							{
								target: {
									opacity: 1,
									rotate: 0,
									rotateX: 20,
									rotateY: 0,
									scale: 0.8,
									skewX: 0,
									skewY: 0,
									x: 0,
									y: -80,
								},
							},
							{
								target: {
									opacity: 1,
									rotate: 0,
									rotateX: 0,
									rotateY: 0,
									scale: 1,
									skewX: 0,
									skewY: 0,
									x: 0,
									y: 0,
								},
							},
						]}
						__framer__transformTrigger={"onInView"}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						background={{
							alt: "An image of Dreelio's dashboard",
							fit: "fill",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 2e3,
							pixelWidth: 2880,
							positionX: "center",
							positionY: "top",
							sizes: componentViewport?.width || "100vw",
							src: "https://framerusercontent.com/images/JeI7uULY0av9DxD7q7NVLTuoNc.png?width=2880&height=2000",
							srcSet:
								"https://framerusercontent.com/images/JeI7uULY0av9DxD7q7NVLTuoNc.png?scale-down-to=512&width=2880&height=2000 512w,https://framerusercontent.com/images/JeI7uULY0av9DxD7q7NVLTuoNc.png?scale-down-to=1024&width=2880&height=2000 1024w,https://framerusercontent.com/images/JeI7uULY0av9DxD7q7NVLTuoNc.png?scale-down-to=2048&width=2880&height=2000 2048w,https://framerusercontent.com/images/JeI7uULY0av9DxD7q7NVLTuoNc.png?width=2880&height=2000 2880w",
						}}
						className={cx(
							scopingClassNames,
							"framer-vci1j0",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"uPrggLWN7"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "2px",
							"--border-color": "rgba(97, 74, 68, 0.2)",
							"--border-left-width": "2px",
							"--border-right-width": "2px",
							"--border-style": "solid",
							"--border-top-width": "2px",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							boxShadow: "0px 4px 50px 0px rgba(97, 74, 68, 0.06)",
							...style,
						}}
					/>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8Qzrr.framer-1com4c1, .framer-8Qzrr .framer-1com4c1 { display: block; }",
	".framer-8Qzrr.framer-vci1j0 { gap: 0px; height: 700px; max-width: 1072px; overflow: hidden; position: relative; width: 1072px; will-change: var(--framer-will-change-override, transform); }",
	'.framer-8Qzrr[data-border="true"]::after, .framer-8Qzrr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerFJMj3QX_F = withCSS(Component, css3, "framer-8Qzrr");
var stdin_default = FramerFJMj3QX_F;
FramerFJMj3QX_F.displayName = "Dashboard Image";
FramerFJMj3QX_F.defaultProps = {
	height: 700,
	width: 1072,
};
addFonts(
	FramerFJMj3QX_F,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/8Gp4oh4ViFouVqNiF5zw/tk1LcK828QSoImVDBEit/h4JcoWJSF.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls,
	ControlType,
	cx as cx2,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/7BT1DhbWPV2VUMvvhRRg/n8gjyLAf8HglAaoqWjwI/PNdcLES0J.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts(["BI;Open Runde/Semibold/v0"]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Runde",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/hG3wmGmFwadB6X5XPVXkMlmLr8o.woff2",
				weight: "600",
			},
		],
	},
];
var css4 = [
	'.framer-JjDAR .framer-styles-preset-5iht5j:not(.rich-text-wrapper), .framer-JjDAR .framer-styles-preset-5iht5j.rich-text-wrapper p { --framer-font-family: "Open Runde", "Open Runde Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-d637c2eb-4179-4d4c-859c-b60c3c740338, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className3 = "framer-JjDAR";

// /:https://framerusercontent.com/modules/8Gp4oh4ViFouVqNiF5zw/tk1LcK828QSoImVDBEit/h4JcoWJSF.js
var enabledGestures = {
	C47CCjYuG: {
		hover: true,
	},
	cMgcydVG6: {
		hover: true,
	},
	OBWsuGAEJ: {
		hover: true,
	},
};
var cycleOrder = ["OBWsuGAEJ", "C47CCjYuG", "cMgcydVG6"];
var serializationHash2 = "framer-GY1mr";
var variantClassNames2 = {
	C47CCjYuG: "framer-v-9t3d8d",
	cMgcydVG6: "framer-v-1ti1e15",
	OBWsuGAEJ: "framer-v-11n4jnd",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	Primary: "OBWsuGAEJ",
	Secondary: "C47CCjYuG",
	Tertiary: "cMgcydVG6",
};
var getProps2 = ({
	border,
	click,
	height,
	id,
	link,
	teriraryButtonText,
	title,
	width,
	...props
}) => {
	return {
		...props,
		ektwzyaAy: title ?? props.ektwzyaAy ?? "Get template",
		FHCLGB0I0:
			teriraryButtonText ??
			props.FHCLGB0I0 ??
			"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
		OnuyxJuml: click ?? props.OnuyxJuml,
		qomMPfTNC: border ??
			props.qomMPfTNC ?? {
				borderColor: "rgb(227, 225, 225)",
				borderStyle: "solid",
				borderWidth: 1,
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "OBWsuGAEJ",
		yPsg9PA2x: link ?? props.yPsg9PA2x,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		ektwzyaAy,
		yPsg9PA2x,
		qomMPfTNC,
		OnuyxJuml,
		FHCLGB0I0,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "OBWsuGAEJ",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1r3dqcs = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (OnuyxJuml) {
			const res = await OnuyxJuml(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className3];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<Link
						href={yPsg9PA2x}
						motionChild={true}
						nodeId={"OBWsuGAEJ"}
						openInNewTab={false}
						scopeId={"h4JcoWJSF"}
						{...addPropertyOverrides(
							{
								cMgcydVG6: {
									openInNewTab: true,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx2(scopingClassNames, "framer-11n4jnd", className4, classNames)} framer-kyiaic`}
							data-border={true}
							data-framer-name={"Primary"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"OBWsuGAEJ"}
							onTap={onTap1r3dqcs}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(227, 225, 225, 0)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								...style,
							}}
							variants={{
								"C47CCjYuG-hover": {
									backgroundColor:
										"var(--token-bcc70d7d-d7d5-49ec-b477-4e5d0ae569c1, rgb(241, 235, 229))",
								},
								"cMgcydVG6-hover": {
									backgroundColor: "rgba(255, 255, 255, 0.2)",
								},
								"OBWsuGAEJ-hover": {
									backgroundColor: "rgba(26, 22, 21, 0.85)",
								},
								C47CCjYuG: {
									backgroundColor:
										"var(--token-8ce91be8-4a20-4537-9973-9f2ad4c619f7, rgb(244, 241, 238))",
								},
								cMgcydVG6: {
									"--border-bottom-width":
										(qomMPfTNC.borderBottomWidth ?? qomMPfTNC.borderWidth) +
										"px",
									"--border-color": qomMPfTNC.borderColor,
									"--border-left-width":
										(qomMPfTNC.borderLeftWidth ?? qomMPfTNC.borderWidth) + "px",
									"--border-right-width":
										(qomMPfTNC.borderRightWidth ?? qomMPfTNC.borderWidth) +
										"px",
									"--border-style": qomMPfTNC.borderStyle,
									"--border-top-width":
										(qomMPfTNC.borderTopWidth ?? qomMPfTNC.borderWidth) + "px",
									backgroundColor: "rgba(255, 255, 255, 0.1)",
								},
							}}
							{...addPropertyOverrides(
								{
									"C47CCjYuG-hover": {
										"data-framer-name": void 0,
									},
									"cMgcydVG6-hover": {
										"data-framer-name": void 0,
									},
									"OBWsuGAEJ-hover": {
										"data-framer-name": void 0,
									},
									C47CCjYuG: {
										"data-framer-name": "Secondary",
									},
									cMgcydVG6: {
										"data-framer-name": "Tertiary",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion2.div
								className={"framer-18171k3"}
								data-framer-name={"Text Container"}
								layoutDependency={layoutDependency}
								layoutId={"G1rzJ0ODJ"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1789mmo"}
									data-framer-name={"Get template"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"GZYMPcCUx"}
									style={{
										"--framer-paragraph-spacing": "0px",
										"--variable-reference-FHCLGB0I0-h4JcoWJSF": FHCLGB0I0,
									}}
									text={ektwzyaAy}
									variants={{
										C47CCjYuG: {
											"--extracted-r6o4lv":
												"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
										},
										cMgcydVG6: {
											"--extracted-r6o4lv":
												"var(--variable-reference-FHCLGB0I0-h4JcoWJSF)",
											"--variable-reference-FHCLGB0I0-h4JcoWJSF": FHCLGB0I0,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											C47CCjYuG: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-5iht5j"}
															data-styles-preset={"PNdcLES0J"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
															}}
														>
															{"Get template"}
														</motion2.p>
													</React2.Fragment>
												),
											},
											cMgcydVG6: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-5iht5j"}
															data-styles-preset={"PNdcLES0J"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--variable-reference-FHCLGB0I0-h4JcoWJSF))",
															}}
														>
															{"Get template"}
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-5iht5j"}
											data-styles-preset={"PNdcLES0J"}
										>
											{"Get template"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1eo985u"}
									data-framer-name={"Get template"}
									fonts={["BI;Open Runde/Semibold/v0"]}
									layoutDependency={layoutDependency}
									layoutId={"dS4eT30j6"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-d637c2eb-4179-4d4c-859c-b60c3c740338, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
										"--variable-reference-FHCLGB0I0-h4JcoWJSF": FHCLGB0I0,
									}}
									text={ektwzyaAy}
									variants={{
										C47CCjYuG: {
											"--extracted-r6o4lv":
												"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
										},
										cMgcydVG6: {
											"--extracted-r6o4lv":
												"var(--variable-reference-FHCLGB0I0-h4JcoWJSF)",
											"--variable-reference-FHCLGB0I0-h4JcoWJSF": FHCLGB0I0,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											C47CCjYuG: {
												children: (
													<React2.Fragment>
														<motion2.p
															style={{
																"--font-selector":
																	"Qkk7T3BlbiBSdW5kZS9TZW1pYm9sZC92MA==",
																"--framer-font-family":
																	'"Open Runde", "Open Runde Placeholder", sans-serif',
																"--framer-font-weight": "600",
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21)))",
															}}
														>
															{"Get template"}
														</motion2.p>
													</React2.Fragment>
												),
											},
											cMgcydVG6: {
												children: (
													<React2.Fragment>
														<motion2.p
															style={{
																"--font-selector":
																	"Qkk7T3BlbiBSdW5kZS9TZW1pYm9sZC92MA==",
																"--framer-font-family":
																	'"Open Runde", "Open Runde Placeholder", sans-serif',
																"--framer-font-weight": "600",
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--variable-reference-FHCLGB0I0-h4JcoWJSF))",
															}}
														>
															{"Get template"}
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											style={{
												"--font-selector":
													"Qkk7T3BlbiBSdW5kZS9TZW1pYm9sZC92MA==",
												"--framer-font-family":
													'"Open Runde", "Open Runde Placeholder", sans-serif',
												"--framer-font-weight": "600",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-d637c2eb-4179-4d4c-859c-b60c3c740338, rgb(255, 255, 255)))",
											}}
										>
											{"Get template"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
						</motion2.a>
					</Link>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-GY1mr.framer-kyiaic, .framer-GY1mr .framer-kyiaic { display: block; }",
	".framer-GY1mr.framer-11n4jnd { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 18px 24px 18px 24px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-GY1mr .framer-18171k3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 19px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-GY1mr .framer-1789mmo, .framer-GY1mr .framer-1eo985u { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; z-index: 1; }",
	".framer-GY1mr.framer-v-11n4jnd.hover .framer-18171k3, .framer-GY1mr.framer-v-9t3d8d.hover .framer-18171k3, .framer-GY1mr.framer-v-1ti1e15.hover .framer-18171k3 { justify-content: flex-end; }",
	...css4,
	'.framer-GY1mr[data-border="true"]::after, .framer-GY1mr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerh4JcoWJSF = withCSS2(Component2, css5, "framer-GY1mr");
var stdin_default2 = Framerh4JcoWJSF;
Framerh4JcoWJSF.displayName = "Main Button";
Framerh4JcoWJSF.defaultProps = {
	height: 55,
	width: 148,
};
addPropertyControls(Framerh4JcoWJSF, {
	variant: {
		options: ["OBWsuGAEJ", "C47CCjYuG", "cMgcydVG6"],
		optionTitles: ["Primary", "Secondary", "Tertiary"],
		title: "Variant",
		type: ControlType.Enum,
	},
	ektwzyaAy: {
		defaultValue: "Get template",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	yPsg9PA2x: {
		title: "Link",
		type: ControlType.Link,
	},
	qomMPfTNC: {
		defaultValue: {
			borderColor: "rgb(227, 225, 225)",
			borderStyle: "solid",
			borderWidth: 1,
		},
		title: "Border",
		type: ControlType.Border,
	},
	OnuyxJuml: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	FHCLGB0I0: {
		defaultValue:
			"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
		title: "Terirary Button Text",
		type: ControlType.Color,
	},
});
addFonts2(
	Framerh4JcoWJSF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Open Runde",
					source: "builtIn",
					style: "normal",
					url: "https://framerusercontent.com/assets/hG3wmGmFwadB6X5XPVXkMlmLr8o.woff2",
					weight: "600",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/MXTbrnyZ1ea7UCQ9BkOR/ffjxQpjFhVhAOLjcIInh/B0Ga6wrMD.js
var MainButtonFonts = getFonts(stdin_default2);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX2(motion3.div),
);
var DashboardImageFonts = getFonts(stdin_default);
var serializationHash3 = "framer-TqnDs";
var variantClassNames3 = {
	jhh85N0W1: "framer-v-vr1el7",
};
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	filter: "blur(10px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition2 = {
	damping: 40,
	delay: 0.05,
	mass: 1,
	stiffness: 163,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0,
	tokenization: "word",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var textEffect1 = {
	effect: animation,
	repeat: false,
	startDelay: 0.1,
	tokenization: "word",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var transition3 = {
	delay: 1.25,
	duration: 0.7,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		defaultVariant: "jhh85N0W1",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.section
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-vr1el7",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"jhh85N0W1"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, var(--token-770c2147-794b-440a-8b9e-6d648b3d844d, rgb(156, 193, 231)) 0%, var(--token-bfa0d0e5-c14b-46a3-b821-f3b67fdfcc02, rgb(237, 223, 208)) 100%)",
							...style,
						}}
					>
						<motion3.div
							className={"framer-1ks373"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"a3YrCgEql"}
						>
							<motion3.div
								className={"framer-ft5v6l"}
								data-framer-name={"Top"}
								layoutDependency={layoutDependency}
								layoutId={"W771PegEl"}
							>
								<motion3.div
									className={"framer-3pg8a9"}
									data-framer-name={"Texts"}
									layoutDependency={layoutDependency}
									layoutId={"EBKbzH5Hn"}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-17v4ul5"}
										data-framer-name={"Run your freelance business like a pro"}
										effect={textEffect}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"j8DrJyz3Q"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.h1
												className={"framer-styles-preset-klyx7p"}
												data-styles-preset={"DrbjvzOzc"}
											>
												{"Run your freelance business like a pro"}
											</motion3.h1>
										</React3.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-2jwnb1"}
										data-framer-name={
											"All-in-one platform for managing clients, projects, and payments\u2014without the chaos. From first contract to final invoice, we\u2019ve got your back."
										}
										effect={textEffect1}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"DMOueQ0pp"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-w183k8"}
												data-styles-preset={"KNLSIQOAc"}
											>
												{
													"All-in-one platform for managing clients, projects, and payments without the chaos. From first contract to final invoice, we\u2019ve got your back."
												}
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								</motion3.div>
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation1}
									className={"framer-lso2at"}
									data-framer-appear-id={"lso2at"}
									data-framer-name={"Button"}
									initial={animation2}
									layoutDependency={layoutDependency}
									layoutId={"Eu0mu9YNO"}
									optimized={true}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "XzDpWUuVS",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={55}
												y={
													(componentViewport?.y || 0) +
													160 +
													0 +
													0 +
													0 +
													0 +
													297.2 +
													0
												}
											>
												<SmartComponentScopedContainer
													className={"framer-dcwptb-container"}
													layoutDependency={layoutDependency}
													layoutId={"gaauaj2hO-container"}
													nodeId={"gaauaj2hO"}
													rendersWithMotion={true}
													scopeId={"B0Ga6wrMD"}
												>
													{_jsx3(stdin_default2, {
														ektwzyaAy: "Try Dreelio free",
														FHCLGB0I0:
															"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
														height: "100%",
														id: "gaauaj2hO",
														layoutId: "gaauaj2hO",
														qomMPfTNC: {
															borderColor: "rgb(227, 225, 225)",
															borderStyle: "solid",
															borderWidth: 1,
														},
														variant: "OBWsuGAEJ",
														width: "100%",
														yPsg9PA2x: resolvedLinks[0],
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													hash: ":VMJGhIahi",
													webPageId: "obBLBu_h4",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider
												height={55}
												y={
													(componentViewport?.y || 0) +
													160 +
													0 +
													0 +
													0 +
													0 +
													297.2 +
													0
												}
											>
												<SmartComponentScopedContainer
													className={"framer-7apd9i-container"}
													layoutDependency={layoutDependency}
													layoutId={"RheKc9HlL-container"}
													nodeId={"RheKc9HlL"}
													rendersWithMotion={true}
													scopeId={"B0Ga6wrMD"}
												>
													{_jsx3(stdin_default2, {
														ektwzyaAy: "See features",
														FHCLGB0I0:
															"var(--token-06ca163c-bd22-4ef3-b608-13ad9cff31ab, rgb(26, 22, 21))",
														height: "100%",
														id: "RheKc9HlL",
														layoutId: "RheKc9HlL",
														qomMPfTNC: {
															borderColor: "rgba(227, 225, 225, 0)",
															borderStyle: "solid",
															borderWidth: 1,
														},
														variant: "cMgcydVG6",
														width: "100%",
														yPsg9PA2x: resolvedLinks1[0],
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</MotionDivWithFXWithOptimizedAppearEffect>
							</motion3.div>
							<ComponentViewportProvider
								height={700}
								width={`min(${componentViewport?.width || "100vw"}, 1072px)`}
								y={(componentViewport?.y || 0) + 160 + 0 + 0 + 416.2}
							>
								<SmartComponentScopedContainer
									className={"framer-1rv6128-container"}
									layoutDependency={layoutDependency}
									layoutId={"N1E7h5mS6-container"}
									nodeId={"N1E7h5mS6"}
									rendersWithMotion={true}
									scopeId={"B0Ga6wrMD"}
									style={{
										transformPerspective: 1e3,
									}}
								>
									{_jsx3(stdin_default, {
										height: "100%",
										id: "N1E7h5mS6",
										layoutId: "N1E7h5mS6",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion3.div>
					</motion3.section>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TqnDs.framer-1fq4xuu, .framer-TqnDs .framer-1fq4xuu { display: block; }",
	".framer-TqnDs.framer-vr1el7 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: 1020px; justify-content: flex-start; min-height: calc(var(--framer-viewport-height, 100vh) * 0.8); overflow: var(--overflow-clip-fallback, clip); padding: 160px 0px 0px 0px; position: relative; width: 1200px; }",
	".framer-TqnDs .framer-1ks373 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1072px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-TqnDs .framer-ft5v6l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; max-width: 792px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TqnDs .framer-3pg8a9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TqnDs .framer-17v4ul5 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-TqnDs .framer-2jwnb1 { flex: none; height: auto; max-width: 700px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-TqnDs .framer-lso2at { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TqnDs .framer-dcwptb-container, .framer-TqnDs .framer-7apd9i-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-TqnDs .framer-1rv6128-container { flex: none; height: 700px; position: relative; width: 100%; }",
	...css,
	...css2,
];
var FramerB0Ga6wrMD = withCSS3(Component3, css6, "framer-TqnDs");
var stdin_default3 = FramerB0Ga6wrMD;
FramerB0Ga6wrMD.displayName = "Hero";
FramerB0Ga6wrMD.defaultProps = {
	height: 1020,
	width: 1200,
};
addFonts3(
	FramerB0Ga6wrMD,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MainButtonFonts,
		...DashboardImageFonts,
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	U_6gacitA: {
		path: "/blog/:slug",
	},
	Wk3v0LVLV: {
		path: "/404",
	},
	XnXPxwXFP: {
		path: "/privacy-policy",
	},
	XzDpWUuVS: {
		path: "/contact-us",
	},
	hsgBIwJa9: {
		path: "/terms-of-use",
	},
	obBLBu_h4: {
		path: "/",
	},
	otG8ouHU2: {
		path: "/blog",
	},
};

// virtual:hero
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b0481a8406af03e25e39e0ef1336071f73860b938bf507a5fcd53a682aa062d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0b0481a8406af03e25e39e0ef1336071f73860b938bf507a5fcd53a682aa062d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var hero_default = ComponentWithRoot;
export { hero_default as default };
