// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cfe7f02456486a1b "TaskFlow (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-XMDMHSV3.js";
import { stdin_default } from "./chunks/chunk-WVXKTZO7.js";
import "./chunks/chunk-6X4H3KEO.js";
import { className, css, fonts } from "./chunks/chunk-U5LHETZW.js";
import { routes } from "./chunks/chunk-UZZEI6KP.js";

// virtual:navbar
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/o5AQrOY8Un4Q20DZCWmS/2jrgtmV3MARpjkRdMeYH/S12d9TJ91.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx3,
	getFonts,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useRouter,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/SBJrwIZt9VadM2WcCSWG/cxVJ0BSSJacIwhURW5gR/EvmLJ7Y03.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["jTGDt_p6D", "fdJxtb2BD"];
var serializationHash = "framer-skRbj";
var variantClassNames = {
	fdJxtb2BD: "framer-v-1mv5qwi",
	jTGDt_p6D: "framer-v-1j6rzx7",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.5,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "fdJxtb2BD",
	Open: "jTGDt_p6D",
};
var getProps = ({ click, height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		BUPHU4mwz: click !== null && click !== void 0 ? click : props.BUPHU4mwz,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "jTGDt_p6D",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		BUPHU4mwz,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "jTGDt_p6D",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1cxyc4c = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (BUPHU4mwz) {
			const res = await BUPHU4mwz(...args);
			if (res === false) return false;
		}
		setVariant("fdJxtb2BD");
	});
	const onTap37u5o0 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (BUPHU4mwz) {
			const res = await BUPHU4mwz(...args);
			if (res === false) return false;
		}
		setVariant("jTGDt_p6D");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1j6rzx7",
							className2,
							classNames,
						)}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"jTGDt_p6D"}
						onTap={onTap1cxyc4c}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								fdJxtb2BD: {
									"data-framer-name": "Close",
									onTap: onTap37u5o0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-rwcrhl"}
							data-framer-name={"Stroke"}
							layoutDependency={layoutDependency}
							layoutId={"dHysBAmKN"}
							style={{
								backgroundColor:
									"var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39))",
								borderBottomLeftRadius: 1e3,
								borderBottomRightRadius: 1e3,
								borderTopLeftRadius: 1e3,
								borderTopRightRadius: 1e3,
								rotate: 0,
							}}
							variants={{
								fdJxtb2BD: {
									rotate: -45,
								},
							}}
						/>
						<motion.div
							className={"framer-cjo0ef"}
							data-framer-name={"Stroke"}
							layoutDependency={layoutDependency}
							layoutId={"ufzSXJNaG"}
							style={{
								backgroundColor:
									"var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39))",
								borderBottomLeftRadius: 1e3,
								borderBottomRightRadius: 1e3,
								borderTopLeftRadius: 1e3,
								borderTopRightRadius: 1e3,
								rotate: 0,
							}}
							variants={{
								fdJxtb2BD: {
									rotate: 45,
								},
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-skRbj.framer-ut8opo, .framer-skRbj .framer-ut8opo { display: block; }",
	".framer-skRbj.framer-1j6rzx7 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: 32px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 32px; }",
	".framer-skRbj .framer-rwcrhl, .framer-skRbj .framer-cjo0ef { flex: none; height: 2px; overflow: hidden; position: relative; width: 24px; will-change: var(--framer-will-change-override, transform); }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-skRbj.framer-1j6rzx7 { gap: 0px; } .framer-skRbj.framer-1j6rzx7 > * { margin: 0px; margin-bottom: calc(6px / 2); margin-top: calc(6px / 2); } .framer-skRbj.framer-1j6rzx7 > :first-child { margin-top: 0px; } .framer-skRbj.framer-1j6rzx7 > :last-child { margin-bottom: 0px; } }",
	".framer-skRbj.framer-v-1mv5qwi .framer-rwcrhl, .framer-skRbj.framer-v-1mv5qwi .framer-cjo0ef { left: calc(50.00000000000002% - 24px / 2); position: absolute; top: calc(50.00000000000002% - 2px / 2); z-index: 1; }",
];
var FramerEvmLJ7Y03 = withCSS(Component, css2, "framer-skRbj");
var stdin_default3 = FramerEvmLJ7Y03;
FramerEvmLJ7Y03.displayName = "Menu Opener";
FramerEvmLJ7Y03.defaultProps = {
	height: 32,
	width: 32,
};
addPropertyControls(FramerEvmLJ7Y03, {
	variant: {
		options: ["jTGDt_p6D", "fdJxtb2BD"],
		optionTitles: ["Open", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	BUPHU4mwz: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerEvmLJ7Y03,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/s2NBPXMk0BdfJLNpZkeU/tv9RP3XOBxLJQZt8IwX5/TJbopPUIQ.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
var enabledGestures = {
	YB5_dAzUh: {
		hover: true,
	},
};
var serializationHash2 = "framer-epadT";
var variantClassNames2 = {
	YB5_dAzUh: "framer-v-1jjlgjb",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, label, link, width, ...props }) => {
	var _ref;
	return {
		...props,
		eOqffHsIV:
			(_ref = label !== null && label !== void 0 ? label : props.eOqffHsIV) !==
				null && _ref !== void 0
				? _ref
				: "Home",
		WYGl0YDKI: link !== null && link !== void 0 ? link : props.WYGl0YDKI,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		WYGl0YDKI,
		eOqffHsIV,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "YB5_dAzUh",
		enabledGestures,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<Link href={WYGl0YDKI} nodeId={"YB5_dAzUh"} smoothScroll={true}>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx2(serializationHash2, ...sharedStyleClassNames, "framer-1jjlgjb", className2, classNames)} framer-17isac4`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"YB5_dAzUh"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								...style,
							}}
							{...addPropertyOverrides2(
								{
									"YB5_dAzUh-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1vpw3zh"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"I7JAItVh7"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={eOqffHsIV}
								variants={{
									"YB5_dAzUh-hover": {
										"--extracted-r6o4lv":
											"var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										"YB5_dAzUh-hover": {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-soml79"}
														data-styles-preset={"XTb7EX2Or"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39)))",
														}}
													>
														{"Home"}
													</motion2.p>
												</React2.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-soml79"}
										data-styles-preset={"XTb7EX2Or"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128)))",
										}}
									>
										{"Home"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
						</motion2.a>
					</Link>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-epadT.framer-17isac4, .framer-epadT .framer-17isac4 { display: block; }",
	".framer-epadT.framer-1jjlgjb { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-epadT .framer-1vpw3zh { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-epadT.framer-1jjlgjb { gap: 0px; } .framer-epadT.framer-1jjlgjb > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-epadT.framer-1jjlgjb > :first-child { margin-left: 0px; } .framer-epadT.framer-1jjlgjb > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerTJbopPUIQ = withCSS2(Component2, css3, "framer-epadT");
var stdin_default4 = FramerTJbopPUIQ;
FramerTJbopPUIQ.displayName = "Navbar Text Link";
FramerTJbopPUIQ.defaultProps = {
	height: 20,
	width: 39,
};
addPropertyControls2(FramerTJbopPUIQ, {
	WYGl0YDKI: {
		title: "Link",
		type: ControlType2.Link,
	},
	eOqffHsIV: {
		defaultValue: "Home",
		displayTextArea: false,
		title: "Label",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerTJbopPUIQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/o5AQrOY8Un4Q20DZCWmS/2jrgtmV3MARpjkRdMeYH/S12d9TJ91.js
var LogotypeFonts = getFonts(stdin_default2);
var MenuOpenerFonts = getFonts(stdin_default3);
var NavbarTextLinkFonts = getFonts(stdin_default4);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var ButtonSecondaryFonts = getFonts(stdin_default);
var cycleOrder2 = [
	"M5GQKyVmq",
	"qBCBjbNoO",
	"Kk8EjWT2s",
	"tLWnOy1In",
	"mBq2V6BC3",
];
var serializationHash3 = "framer-d8fN5";
var variantClassNames3 = {
	Kk8EjWT2s: "framer-v-jo5ka",
	M5GQKyVmq: "framer-v-1swh7ch",
	mBq2V6BC3: "framer-v-lmn8f2",
	qBCBjbNoO: "framer-v-13ck3pb",
	tLWnOy1In: "framer-v-1n53p6f",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 15,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.3,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition13,
	x: 0,
	y: 0,
};
var transition3 = {
	bounce: 0.3,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var transition4 = {
	bounce: 0.2,
	delay: 0.1,
	duration: 0.3,
	type: "spring",
};
var transition5 = {
	bounce: 0.3,
	delay: 0.1,
	duration: 0.6,
	type: "spring",
};
var transition6 = {
	bounce: 0.2,
	delay: 0.4,
	duration: 0.3,
	type: "spring",
};
var transition7 = {
	bounce: 0.3,
	delay: 0.3,
	duration: 0.6,
	type: "spring",
};
var transition8 = {
	bounce: 0.2,
	delay: 0.5,
	duration: 0.3,
	type: "spring",
};
var transition9 = {
	bounce: 0.3,
	delay: 0.4,
	duration: 0.6,
	type: "spring",
};
var transition10 = {
	bounce: 0.2,
	delay: 0.7,
	duration: 0.3,
	type: "spring",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 5,
};
var transition11 = {
	bounce: 0.3,
	delay: 0.6,
	duration: 0.6,
	type: "spring",
};
var transition122 = {
	bounce: 0.3,
	delay: 0.9,
	duration: 0.6,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var humanReadableVariantMap2 = {
	"Mobile Close": "tLWnOy1In",
	"Mobile Open": "mBq2V6BC3",
	"Tablet Close": "qBCBjbNoO",
	"Tablet Open": "Kk8EjWT2s",
	Desktop: "M5GQKyVmq",
};
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "M5GQKyVmq",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder2,
		defaultVariant: "M5GQKyVmq",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const BUPHU4mwzu4a84e = activeVariantCallback(async (...args) => {
		setVariant("Kk8EjWT2s");
	});
	const BUPHU4mwz18t1b3e = activeVariantCallback(async (...args) => {
		setVariant("qBCBjbNoO");
	});
	const BUPHU4mwz1ds4iee = activeVariantCallback(async (...args) => {
		setVariant("mBq2V6BC3");
	});
	const BUPHU4mwz1s4rbbs = activeVariantCallback(async (...args) => {
		setVariant("tLWnOy1In");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			["qBCBjbNoO", "Kk8EjWT2s", "tLWnOy1In", "mBq2V6BC3"].includes(baseVariant)
		)
			return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["qBCBjbNoO", "tLWnOy1In"].includes(baseVariant)) return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.nav
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-1swh7ch",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"M5GQKyVmq"}
						ref={refBinding}
						style={{
							backdropFilter: "blur(10px)",
							backgroundColor: "rgba(249, 250, 251, 0.8)",
							borderBottomLeftRadius: 0,
							borderBottomRightRadius: 0,
							boxShadow: "none",
							WebkitBackdropFilter: "blur(10px)",
							...style,
						}}
						variants={{
							Kk8EjWT2s: {
								backgroundColor:
									"var(--token-08f2dbd6-30f3-4b80-b3ec-25d8f6146ee9, rgb(255, 255, 255))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								boxShadow:
									"0px 0.6021873017743928px 1.5656869846134214px -0.5833333333333333px rgba(0, 0, 0, 0.06), 0px 2.288533303243457px 5.950186588432988px -1.1666666666666665px rgba(0, 0, 0, 0.06), 0px 10px 26px -1.75px rgba(0, 0, 0, 0.1)",
							},
							mBq2V6BC3: {
								backgroundColor:
									"var(--token-08f2dbd6-30f3-4b80-b3ec-25d8f6146ee9, rgb(255, 255, 255))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								boxShadow:
									"0px 0.6021873017743928px 1.5656869846134214px -0.5833333333333333px rgba(0, 0, 0, 0.06), 0px 2.288533303243457px 5.950186588432988px -1.1666666666666665px rgba(0, 0, 0, 0.06), 0px 10px 26px -1.75px rgba(0, 0, 0, 0.1)",
							},
							tLWnOy1In: {
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								boxShadow: "none",
							},
						}}
						{...addPropertyOverrides3(
							{
								Kk8EjWT2s: {
									"data-framer-name": "Tablet Open",
								},
								mBq2V6BC3: {
									"data-framer-name": "Mobile Open",
								},
								qBCBjbNoO: {
									"data-framer-name": "Tablet Close",
								},
								tLWnOy1In: {
									"data-framer-name": "Mobile Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-4ihmu6"}
							data-framer-name={"Padding"}
							layoutDependency={layoutDependency}
							layoutId={"VITVgRZhZ"}
						>
							<motion3.div
								className={"framer-f5ibfo"}
								data-framer-name={"Menu and Logo"}
								layoutDependency={layoutDependency}
								layoutId={"HghxCsdBO"}
							>
								<motion3.div
									className={"framer-10vo111"}
									data-framer-name={"Logo/Opener"}
									layoutDependency={layoutDependency}
									layoutId={"KPeH21YVA"}
								>
									<ComponentViewportProvider
										height={32}
										width={"135px"}
										y={
											(componentViewport?.y || 0) +
											(24 + ((componentViewport?.height || 88) - 48 - 40) / 2) +
											4 +
											0 +
											0
										}
										{...addPropertyOverrides3(
											{
												Kk8EjWT2s: {
													y:
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 200) - 48 - 364) /
																2) +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												mBq2V6BC3: {
													y:
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 200) - 48 - 380) /
																2) +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												qBCBjbNoO: {
													y:
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 80) - 48 - 32) /
																2) +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												tLWnOy1In: {
													y:
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 200) - 48 - 32) /
																2) +
														0 +
														0 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-22hlde-container"}
											layoutDependency={layoutDependency}
											layoutId={"uSfTbM1wz-container"}
											nodeId={"uSfTbM1wz"}
											rendersWithMotion={true}
											scopeId={"S12d9TJ91"}
										>
											{_jsx3(stdin_default2, {
												height: "100%",
												id: "uSfTbM1wz",
												layoutId: "uSfTbM1wz",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: "nmx1zdtT8",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									{isDisplayed() && (
										<ComponentViewportProvider
											{...addPropertyOverrides3(
												{
													Kk8EjWT2s: {
														height: 32,
														width: "32px",
														y:
															(componentViewport?.y || 0) +
															(24 +
																((componentViewport?.height || 200) -
																	48 -
																	364) /
																	2) +
															0 +
															0 +
															0 +
															0 +
															0,
													},
													mBq2V6BC3: {
														height: 32,
														width: "32px",
														y:
															(componentViewport?.y || 0) +
															(24 +
																((componentViewport?.height || 200) -
																	48 -
																	380) /
																	2) +
															0 +
															0 +
															0 +
															0 +
															0,
													},
													qBCBjbNoO: {
														height: 32,
														width: "32px",
														y:
															(componentViewport?.y || 0) +
															(24 +
																((componentViewport?.height || 80) - 48 - 32) /
																	2) +
															0 +
															0 +
															0 +
															0 +
															0,
													},
													tLWnOy1In: {
														height: 32,
														width: "32px",
														y:
															(componentViewport?.y || 0) +
															(24 +
																((componentViewport?.height || 200) - 48 - 32) /
																	2) +
															0 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-o3gyct-container"}
												layoutDependency={layoutDependency}
												layoutId={"nl0Ohknaf-container"}
												nodeId={"nl0Ohknaf"}
												rendersWithMotion={true}
												scopeId={"S12d9TJ91"}
											>
												{_jsx3(stdin_default3, {
													height: "100%",
													id: "nl0Ohknaf",
													layoutId: "nl0Ohknaf",
													style: {
														height: "100%",
														width: "100%",
													},
													variant: "jTGDt_p6D",
													width: "100%",
													...addPropertyOverrides3(
														{
															Kk8EjWT2s: {
																BUPHU4mwz: BUPHU4mwz18t1b3e,
																variant: "fdJxtb2BD",
															},
															mBq2V6BC3: {
																BUPHU4mwz: BUPHU4mwz1s4rbbs,
																variant: "fdJxtb2BD",
															},
															qBCBjbNoO: {
																BUPHU4mwz: BUPHU4mwzu4a84e,
															},
															tLWnOy1In: {
																BUPHU4mwz: BUPHU4mwz1ds4iee,
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</motion3.div>
								{isDisplayed1() && (
									<motion3.div
										className={"framer-1suk7gy"}
										data-framer-name={"Menu"}
										layoutDependency={layoutDependency}
										layoutId={"kp6fkNBBO"}
									>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													height={20}
													y={
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 88) - 48 - 40) /
																2) +
														4 +
														6 +
														0
													}
													{...addPropertyOverrides3(
														{
															Kk8EjWT2s: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			364) /
																			2) +
																	0 +
																	0 +
																	0 +
																	64 +
																	0 +
																	0,
															},
															mBq2V6BC3: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			380) /
																			2) +
																	0 +
																	0 +
																	0 +
																	96 +
																	0 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainerWithFX
														className={"framer-1oqy8a-container"}
														layoutDependency={layoutDependency}
														layoutId={"lrz8vP6hr-container"}
														nodeId={"lrz8vP6hr"}
														rendersWithMotion={true}
														scopeId={"S12d9TJ91"}
														{...addPropertyOverrides3(
															{
																Kk8EjWT2s: {
																	__framer__animate: {
																		transition: transition2,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
																mBq2V6BC3: {
																	__framer__animate: {
																		transition: transition3,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														{_jsx3(stdin_default4, {
															eOqffHsIV: "Home",
															height: "100%",
															id: "lrz8vP6hr",
															layoutId: "lrz8vP6hr",
															width: "100%",
															WYGl0YDKI: resolvedLinks[0],
															...addPropertyOverrides3(
																{
																	Kk8EjWT2s: {
																		WYGl0YDKI: resolvedLinks[1],
																	},
																	mBq2V6BC3: {
																		WYGl0YDKI: resolvedLinks[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainerWithFX>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":Csv1Mhqex",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":Csv1Mhqex",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":Csv1Mhqex",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks1) => (
												<ComponentViewportProvider
													height={20}
													y={
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 88) - 48 - 40) /
																2) +
														4 +
														6 +
														0
													}
													{...addPropertyOverrides3(
														{
															Kk8EjWT2s: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			364) /
																			2) +
																	0 +
																	0 +
																	0 +
																	64 +
																	0 +
																	52,
															},
															mBq2V6BC3: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			380) /
																			2) +
																	0 +
																	0 +
																	0 +
																	96 +
																	0 +
																	52,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainerWithFX
														className={"framer-o2ns67-container"}
														layoutDependency={layoutDependency}
														layoutId={"im8pDy8Jb-container"}
														nodeId={"im8pDy8Jb"}
														rendersWithMotion={true}
														scopeId={"S12d9TJ91"}
														{...addPropertyOverrides3(
															{
																Kk8EjWT2s: {
																	__framer__animate: {
																		transition: transition4,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
																mBq2V6BC3: {
																	__framer__animate: {
																		transition: transition5,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														{_jsx3(stdin_default4, {
															eOqffHsIV: "Features",
															height: "100%",
															id: "im8pDy8Jb",
															layoutId: "im8pDy8Jb",
															width: "100%",
															WYGl0YDKI: resolvedLinks1[0],
															...addPropertyOverrides3(
																{
																	Kk8EjWT2s: {
																		WYGl0YDKI: resolvedLinks1[1],
																	},
																	mBq2V6BC3: {
																		WYGl0YDKI: resolvedLinks1[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainerWithFX>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":j_PRT5VgI",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":j_PRT5VgI",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":j_PRT5VgI",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks2) => (
												<ComponentViewportProvider
													height={20}
													y={
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 88) - 48 - 40) /
																2) +
														4 +
														6 +
														0
													}
													{...addPropertyOverrides3(
														{
															Kk8EjWT2s: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			364) /
																			2) +
																	0 +
																	0 +
																	0 +
																	64 +
																	0 +
																	104,
															},
															mBq2V6BC3: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			380) /
																			2) +
																	0 +
																	0 +
																	0 +
																	96 +
																	0 +
																	104,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainerWithFX
														className={"framer-11817yp-container"}
														layoutDependency={layoutDependency}
														layoutId={"L5RnFNIIf-container"}
														nodeId={"L5RnFNIIf"}
														rendersWithMotion={true}
														scopeId={"S12d9TJ91"}
														{...addPropertyOverrides3(
															{
																Kk8EjWT2s: {
																	__framer__animate: {
																		transition: transition6,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
																mBq2V6BC3: {
																	__framer__animate: {
																		transition: transition7,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														{_jsx3(stdin_default4, {
															eOqffHsIV: "Pricing",
															height: "100%",
															id: "L5RnFNIIf",
															layoutId: "L5RnFNIIf",
															width: "100%",
															WYGl0YDKI: resolvedLinks2[0],
															...addPropertyOverrides3(
																{
																	Kk8EjWT2s: {
																		WYGl0YDKI: resolvedLinks2[1],
																	},
																	mBq2V6BC3: {
																		WYGl0YDKI: resolvedLinks2[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainerWithFX>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "iaDFKtQ2m",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "iaDFKtQ2m",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "iaDFKtQ2m",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks3) => (
												<ComponentViewportProvider
													height={20}
													y={
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 88) - 48 - 40) /
																2) +
														4 +
														6 +
														0
													}
													{...addPropertyOverrides3(
														{
															Kk8EjWT2s: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			364) /
																			2) +
																	0 +
																	0 +
																	0 +
																	64 +
																	0 +
																	156,
															},
															mBq2V6BC3: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			380) /
																			2) +
																	0 +
																	0 +
																	0 +
																	96 +
																	0 +
																	156,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainerWithFX
														className={"framer-pq8kzi-container"}
														layoutDependency={layoutDependency}
														layoutId={"KIbDcI8HN-container"}
														nodeId={"KIbDcI8HN"}
														rendersWithMotion={true}
														scopeId={"S12d9TJ91"}
														{...addPropertyOverrides3(
															{
																Kk8EjWT2s: {
																	__framer__animate: {
																		transition: transition8,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
																mBq2V6BC3: {
																	__framer__animate: {
																		transition: transition9,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														{_jsx3(stdin_default4, {
															eOqffHsIV: "About",
															height: "100%",
															id: "KIbDcI8HN",
															layoutId: "KIbDcI8HN",
															width: "100%",
															WYGl0YDKI: resolvedLinks3[0],
															...addPropertyOverrides3(
																{
																	Kk8EjWT2s: {
																		WYGl0YDKI: resolvedLinks3[1],
																	},
																	mBq2V6BC3: {
																		WYGl0YDKI: resolvedLinks3[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainerWithFX>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "LaYOcZez6",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "LaYOcZez6",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "LaYOcZez6",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks4) => (
												<ComponentViewportProvider
													height={20}
													y={
														(componentViewport?.y || 0) +
														(24 +
															((componentViewport?.height || 88) - 48 - 40) /
																2) +
														4 +
														6 +
														0
													}
													{...addPropertyOverrides3(
														{
															Kk8EjWT2s: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			364) /
																			2) +
																	0 +
																	0 +
																	0 +
																	64 +
																	0 +
																	208,
															},
															mBq2V6BC3: {
																y:
																	(componentViewport?.y || 0) +
																	(24 +
																		((componentViewport?.height || 200) -
																			48 -
																			380) /
																			2) +
																	0 +
																	0 +
																	0 +
																	96 +
																	0 +
																	208,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainerWithFX
														className={"framer-12g8b2j-container"}
														layoutDependency={layoutDependency}
														layoutId={"NXJ9F02fN-container"}
														nodeId={"NXJ9F02fN"}
														rendersWithMotion={true}
														scopeId={"S12d9TJ91"}
														{...addPropertyOverrides3(
															{
																Kk8EjWT2s: {
																	__framer__animate: {
																		transition: transition10,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
																mBq2V6BC3: {
																	__framer__animate: {
																		transition: transition11,
																	},
																	__framer__animateOnce: false,
																	__framer__enter: animation2,
																	__framer__exit: animation1,
																	__framer__styleAppearEffectEnabled: true,
																	__framer__threshold: 0.5,
																	__perspectiveFX: false,
																	__smartComponentFX: true,
																	__targetOpacity: 1,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														{_jsx3(stdin_default4, {
															eOqffHsIV: "Blog",
															height: "100%",
															id: "NXJ9F02fN",
															layoutId: "NXJ9F02fN",
															width: "100%",
															WYGl0YDKI: resolvedLinks4[0],
															...addPropertyOverrides3(
																{
																	Kk8EjWT2s: {
																		WYGl0YDKI: resolvedLinks4[1],
																	},
																	mBq2V6BC3: {
																		WYGl0YDKI: resolvedLinks4[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainerWithFX>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion3.div>
								)}
							</motion3.div>
							{isDisplayed1() && (
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "f1s_Yp8dS",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "f1s_Yp8dS",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "f1s_Yp8dS",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks5) => (
										<ComponentViewportProvider
											height={40}
											y={
												(componentViewport?.y || 0) +
												(24 +
													((componentViewport?.height || 88) - 48 - 40) / 2) +
												0
											}
											{...addPropertyOverrides3(
												{
													Kk8EjWT2s: {
														width: "150px",
														y:
															(componentViewport?.y || 0) +
															(24 +
																((componentViewport?.height || 200) -
																	48 -
																	364) /
																	2) +
															0 +
															324,
													},
													mBq2V6BC3: {
														width: `min(${componentViewport?.width || "100vw"} - 40px, 1440px)`,
														y:
															(componentViewport?.y || 0) +
															(24 +
																((componentViewport?.height || 200) -
																	48 -
																	380) /
																	2) +
															0 +
															340,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												className={"framer-1s5n2tf-container"}
												layoutDependency={layoutDependency}
												layoutId={"rTbjc5Zch-container"}
												nodeId={"rTbjc5Zch"}
												rendersWithMotion={true}
												scopeId={"S12d9TJ91"}
												{...addPropertyOverrides3(
													{
														mBq2V6BC3: {
															__framer__animate: {
																transition: transition122,
															},
															__framer__animateOnce: false,
															__framer__enter: animation,
															__framer__exit: animation1,
															__framer__styleAppearEffectEnabled: true,
															__framer__threshold: 0.5,
															__perspectiveFX: false,
															__smartComponentFX: true,
															__targetOpacity: 1,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												{_jsx3(stdin_default, {
													bL9DUTLS5: "Contact us",
													height: "100%",
													id: "rTbjc5Zch",
													kI0zFLUtw: resolvedLinks5[0],
													layoutId: "rTbjc5Zch",
													variant: "H2RtDWI43",
													width: "100%",
													...addPropertyOverrides3(
														{
															Kk8EjWT2s: {
																kI0zFLUtw: resolvedLinks5[1],
																style: {
																	width: "100%",
																},
															},
															mBq2V6BC3: {
																kI0zFLUtw: resolvedLinks5[2],
																style: {
																	width: "100%",
																},
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							)}
						</motion3.div>
					</motion3.nav>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-d8fN5.framer-u7ttef, .framer-d8fN5 .framer-u7ttef { display: block; }",
	".framer-d8fN5.framer-1swh7ch { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 24px 80px 24px 80px; position: relative; width: 1200px; }",
	".framer-d8fN5 .framer-4ihmu6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-d8fN5 .framer-f5ibfo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-d8fN5 .framer-10vo111 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-d8fN5 .framer-22hlde-container { flex: none; height: 32px; position: relative; width: 135px; }",
	".framer-d8fN5 .framer-o3gyct-container { flex: none; height: 32px; position: relative; width: 32px; }",
	".framer-d8fN5 .framer-1suk7gy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-d8fN5 .framer-1oqy8a-container, .framer-d8fN5 .framer-o2ns67-container, .framer-d8fN5 .framer-11817yp-container, .framer-d8fN5 .framer-pq8kzi-container, .framer-d8fN5 .framer-12g8b2j-container, .framer-d8fN5 .framer-1s5n2tf-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-d8fN5.framer-v-13ck3pb.framer-1swh7ch, .framer-d8fN5.framer-v-jo5ka.framer-1swh7ch { overflow: visible; padding: 24px 32px 24px 32px; width: 810px; }",
	".framer-d8fN5.framer-v-13ck3pb .framer-4ihmu6, .framer-d8fN5.framer-v-1n53p6f .framer-4ihmu6 { flex-direction: column; gap: 10px; justify-content: flex-start; }",
	".framer-d8fN5.framer-v-13ck3pb .framer-f5ibfo, .framer-d8fN5.framer-v-1n53p6f .framer-f5ibfo, .framer-d8fN5.framer-v-lmn8f2 .framer-f5ibfo { flex-direction: column; overflow: visible; width: 100%; }",
	".framer-d8fN5.framer-v-13ck3pb .framer-10vo111, .framer-d8fN5.framer-v-jo5ka .framer-10vo111, .framer-d8fN5.framer-v-1n53p6f .framer-10vo111, .framer-d8fN5.framer-v-lmn8f2 .framer-10vo111 { gap: unset; justify-content: space-between; width: 100%; }",
	".framer-d8fN5.framer-v-jo5ka .framer-4ihmu6 { flex-direction: column; gap: 32px; justify-content: flex-start; }",
	".framer-d8fN5.framer-v-jo5ka .framer-f5ibfo { flex-direction: column; gap: 32px; overflow: visible; width: 100%; }",
	".framer-d8fN5.framer-v-jo5ka .framer-1suk7gy { flex-direction: column; gap: 32px; overflow: visible; }",
	".framer-d8fN5.framer-v-jo5ka .framer-1s5n2tf-container { width: 150px; }",
	".framer-d8fN5.framer-v-1n53p6f.framer-1swh7ch, .framer-d8fN5.framer-v-lmn8f2.framer-1swh7ch { overflow: visible; padding: 24px 20px 24px 20px; width: 390px; }",
	".framer-d8fN5.framer-v-lmn8f2 .framer-4ihmu6 { flex-direction: column; gap: 16px; justify-content: flex-start; }",
	".framer-d8fN5.framer-v-lmn8f2 .framer-1suk7gy { flex-direction: column; gap: 32px; }",
	".framer-d8fN5.framer-v-lmn8f2 .framer-1s5n2tf-container { width: 100%; }",
];
var FramerS12d9TJ91 = withCSS3(Component3, css4, "framer-d8fN5");
var stdin_default5 = FramerS12d9TJ91;
FramerS12d9TJ91.displayName = "Navbar";
FramerS12d9TJ91.defaultProps = {
	height: 88,
	width: 1200,
};
addPropertyControls3(FramerS12d9TJ91, {
	variant: {
		options: ["M5GQKyVmq", "qBCBjbNoO", "Kk8EjWT2s", "tLWnOy1In", "mBq2V6BC3"],
		optionTitles: [
			"Desktop",
			"Tablet Close",
			"Tablet Open",
			"Mobile Close",
			"Mobile Open",
		],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts3(
	FramerS12d9TJ91,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LogotypeFonts,
		...MenuOpenerFonts,
		...NavbarTextLinkFonts,
		...ButtonSecondaryFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navbar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "tLWnOy1In",
	md: "qBCBjbNoO",
	xl: "M5GQKyVmq",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavbarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var navbar_default = ComponentWithRoot;
export { navbar_default as default };
