// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cfe7f02456486a1b "TaskFlow (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-UZZEI6KP.js";

// virtual:social-icon
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/htPq5vYIxYYrDPnGUsWA/72Y2FHzeySMXCV9UJj9I/EKgIGv7NI.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	w6mxPbg0s: {
		hover: true,
	},
};
var serializationHash = "framer-HDwfU";
var variantClassNames = {
	w6mxPbg0s: "framer-v-uafyco",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, link, width, ...props }) => {
	var _ref;
	return {
		...props,
		vdadLns5L:
			(_ref = image !== null && image !== void 0 ? image : props.vdadLns5L) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/0nYURcoWcvLE3lDUB4Np8KcaGzw.png",
					},
		YZ5xeanMe: link !== null && link !== void 0 ? link : props.YZ5xeanMe,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		YZ5xeanMe,
		vdadLns5L,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "w6mxPbg0s",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={YZ5xeanMe} nodeId={"w6mxPbg0s"} smoothScroll={true}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-uafyco", className, classNames)} framer-19jmhkn`}
							data-border={true}
							data-framer-name={"H"}
							layoutDependency={layoutDependency}
							layoutId={"w6mxPbg0s"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(229, 231, 235, 0)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(255, 255, 255, 0)",
								borderBottomLeftRadius: 6,
								borderBottomRightRadius: 6,
								borderTopLeftRadius: 6,
								borderTopRightRadius: 6,
								...style,
							}}
							variants={{
								"w6mxPbg0s-hover": {
									"--border-color":
										"var(--token-7e2cee24-41e3-44f2-9710-90e095fcc68d, rgb(229, 231, 235))",
									backgroundColor: "rgb(255, 255, 255)",
								},
							}}
							{...addPropertyOverrides(
								{
									"w6mxPbg0s-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											(4 +
												(((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.height) || 32) -
													8 -
													24) /
													2),
									),
									sizes: "24px",
									...toResponsiveImage(vdadLns5L),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-92n74m"}
								layoutDependency={layoutDependency}
								layoutId={"vBgJZwhoG"}
							/>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-HDwfU.framer-19jmhkn, .framer-HDwfU .framer-19jmhkn { display: block; }",
	".framer-HDwfU.framer-uafyco { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 4px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-HDwfU .framer-92n74m { flex: none; height: 24px; overflow: visible; position: relative; width: 24px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-HDwfU.framer-uafyco { gap: 0px; } .framer-HDwfU.framer-uafyco > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-HDwfU.framer-uafyco > :first-child { margin-left: 0px; } .framer-HDwfU.framer-uafyco > :last-child { margin-right: 0px; } }",
	'.framer-HDwfU[data-border="true"]::after, .framer-HDwfU [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerEKgIGv7NI = withCSS(Component, css, "framer-HDwfU");
var stdin_default = FramerEKgIGv7NI;
FramerEKgIGv7NI.displayName = "Social Icon";
FramerEKgIGv7NI.defaultProps = {
	height: 32,
	width: 32,
};
addPropertyControls(FramerEKgIGv7NI, {
	YZ5xeanMe: {
		title: "Link",
		type: ControlType.Link,
	},
	vdadLns5L: {
		__defaultAssetReference:
			"data:framer/asset-reference,0nYURcoWcvLE3lDUB4Np8KcaGzw.png?originalFilename=Avatar+Image-4.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerEKgIGv7NI,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:social-icon
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SocialIconFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var social_icon_default = ComponentWithRoot;
export { social_icon_default as default };
