// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cfe7f02456486a1b "TaskFlow (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-3FT6E64W.js";
import "./chunks/chunk-XALRBIFG.js";
import { className, css, fonts } from "./chunks/chunk-7QNJWUDS.js";
import { stdin_default } from "./chunks/chunk-5AST346G.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-EGCCNRVP.js";
import "./chunks/chunk-U5LHETZW.js";
import { routes } from "./chunks/chunk-UZZEI6KP.js";

// virtual:solutions
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rKkIbwnZPhu5pCIqkRUm/O9HDGEetVH9e0atYtGby/lk3otI4uM.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BadgeMiniFonts = getFonts(stdin_default);
var SloutionCardFonts = getFonts(stdin_default2);
var cycleOrder = ["C3YPHn0db", "xC_Vf1okp", "pNQRoApTa"];
var serializationHash = "framer-tpCXd";
var variantClassNames = {
	C3YPHn0db: "framer-v-11vlxt1",
	pNQRoApTa: "framer-v-xw90qi",
	xC_Vf1okp: "framer-v-1b5x178",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "C3YPHn0db",
	Phone: "pNQRoApTa",
	Tablet: "xC_Vf1okp",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "C3YPHn0db",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "C3YPHn0db",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-11vlxt1",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"C3YPHn0db"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-08f2dbd6-30f3-4b80-b3ec-25d8f6146ee9, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								pNQRoApTa: {
									"data-framer-name": "Phone",
								},
								xC_Vf1okp: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1mvp7t0"}
							data-framer-name={"Padding"}
							layoutDependency={layoutDependency}
							layoutId={"HFWcKxaIN"}
						>
							<motion.div
								className={"framer-1husmtz"}
								data-framer-name={"Head Content"}
								layoutDependency={layoutDependency}
								layoutId={"CrEpjH4I9"}
							>
								<ComponentViewportProvider
									height={28}
									y={
										(componentViewport?.y || 0) +
										(120 +
											((componentViewport?.height || 654) - 240 - 510) / 2) +
										0 +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											pNQRoApTa: {
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 1104) - 120 - 942) /
															2) +
													0 +
													0 +
													0 +
													0,
											},
											xC_Vf1okp: {
												y:
													(componentViewport?.y || 0) +
													(80 +
														((componentViewport?.height || 934) - 160 - 942) /
															2) +
													0 +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1gldzm-container"}
										layoutDependency={layoutDependency}
										layoutId={"W_kFhwccm-container"}
										nodeId={"W_kFhwccm"}
										rendersWithMotion={true}
										scopeId={"lk3otI4uM"}
									>
										{_jsx(stdin_default, {
											gQqOpdg6s: "Solutions",
											height: "100%",
											id: "W_kFhwccm",
											layoutId: "W_kFhwccm",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion.div
									className={"framer-mx6zsp"}
									data-framer-name={"Head Text"}
									layoutDependency={layoutDependency}
									layoutId={"MuDKwaNRL"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-79oxqg"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"s4KLlVVAl"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h2
												className={"framer-styles-preset-1owo7gc"}
												data-styles-preset={"IBoZbZL0y"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39)))",
												}}
											>
												{"Solutions for Every Team"}
											</motion.h2>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-dacxfe"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ziGVABS3x"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1f6wsl4"}
												data-styles-preset={"VYWldt3Ia"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128)))",
												}}
											>
												{"Customizable workflows for any team size or industry"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-116twm6"}
								data-framer-name={"Benefits Group"}
								layoutDependency={layoutDependency}
								layoutId={"T1q_Qyk3n"}
							>
								<ComponentViewportProvider
									height={200}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px) - 64px) / 5, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(120 +
											((componentViewport?.height || 654) - 240 - 510) / 2) +
										0 +
										310 +
										0
									}
									{...addPropertyOverrides(
										{
											pNQRoApTa: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px) - 16px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 1104) - 120 - 942) /
															2) +
													0 +
													310 +
													0 +
													0,
											},
											xC_Vf1okp: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px) - 16px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													(80 +
														((componentViewport?.height || 934) - 160 - 942) /
															2) +
													0 +
													310 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-irtgjy-container"}
										layoutDependency={layoutDependency}
										layoutId={"dhij5AAI_-container"}
										nodeId={"dhij5AAI_"}
										rendersWithMotion={true}
										scopeId={"lk3otI4uM"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "dhij5AAI_",
											layoutId: "dhij5AAI_",
											rsZPcYcNG: addImageAlt(
												{
													pixelHeight: 65,
													pixelWidth: 65,
													src: "https://framerusercontent.com/images/b0NRR7pWYpkak5V1OxpCiFpFhEE.svg?width=65&height=65",
												},
												"",
											),
											RwK8T9gAW: "Project Management",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={200}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px) - 64px) / 5, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(120 +
											((componentViewport?.height || 654) - 240 - 510) / 2) +
										0 +
										310 +
										0
									}
									{...addPropertyOverrides(
										{
											pNQRoApTa: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px) - 16px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 1104) - 120 - 942) /
															2) +
													0 +
													310 +
													0 +
													0,
											},
											xC_Vf1okp: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px) - 16px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													(80 +
														((componentViewport?.height || 934) - 160 - 942) /
															2) +
													0 +
													310 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-u4urm3-container"}
										layoutDependency={layoutDependency}
										layoutId={"O25Iuof9O-container"}
										nodeId={"O25Iuof9O"}
										rendersWithMotion={true}
										scopeId={"lk3otI4uM"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "O25Iuof9O",
											layoutId: "O25Iuof9O",
											rsZPcYcNG: addImageAlt(
												{
													pixelHeight: 65,
													pixelWidth: 65,
													src: "https://framerusercontent.com/images/oxPEUkeW4NjEFBiaCEiKcUHy8fc.svg?width=65&height=65",
												},
												"",
											),
											RwK8T9gAW: "Document Collaboration",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={200}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px) - 64px) / 5, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(120 +
											((componentViewport?.height || 654) - 240 - 510) / 2) +
										0 +
										310 +
										0
									}
									{...addPropertyOverrides(
										{
											pNQRoApTa: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px) - 16px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 1104) - 120 - 942) /
															2) +
													0 +
													310 +
													0 +
													216,
											},
											xC_Vf1okp: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px) - 16px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													(80 +
														((componentViewport?.height || 934) - 160 - 942) /
															2) +
													0 +
													310 +
													0 +
													216,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-kgck9-container"}
										layoutDependency={layoutDependency}
										layoutId={"v7ejEkFZu-container"}
										nodeId={"v7ejEkFZu"}
										rendersWithMotion={true}
										scopeId={"lk3otI4uM"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "v7ejEkFZu",
											layoutId: "v7ejEkFZu",
											rsZPcYcNG: addImageAlt(
												{
													pixelHeight: 65,
													pixelWidth: 65,
													src: "https://framerusercontent.com/images/NAMws0RjG4dFlU7lu6e69zaA.svg?width=65&height=65",
												},
												"",
											),
											RwK8T9gAW: "Meeting Management",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={200}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px) - 64px) / 5, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(120 +
											((componentViewport?.height || 654) - 240 - 510) / 2) +
										0 +
										310 +
										0
									}
									{...addPropertyOverrides(
										{
											pNQRoApTa: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px) - 16px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 1104) - 120 - 942) /
															2) +
													0 +
													310 +
													0 +
													216,
											},
											xC_Vf1okp: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px) - 16px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													(80 +
														((componentViewport?.height || 934) - 160 - 942) /
															2) +
													0 +
													310 +
													0 +
													216,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-xi28ni-container"}
										layoutDependency={layoutDependency}
										layoutId={"Es_lTEokd-container"}
										nodeId={"Es_lTEokd"}
										rendersWithMotion={true}
										scopeId={"lk3otI4uM"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "Es_lTEokd",
											layoutId: "Es_lTEokd",
											rsZPcYcNG: addImageAlt(
												{
													pixelHeight: 65,
													pixelWidth: 65,
													src: "https://framerusercontent.com/images/cNzqrtjo3MwAqa6Ed1VFOFozQ.svg?width=65&height=65",
												},
												"",
											),
											RwK8T9gAW: "Goal \u2028Tracking",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={200}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 160px, 1px), 1440px) - 64px) / 5, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(120 +
											((componentViewport?.height || 654) - 240 - 510) / 2) +
										0 +
										310 +
										0
									}
									{...addPropertyOverrides(
										{
											pNQRoApTa: {
												width: `calc(max((min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1440px) - 16px) / 2, 50px) * 2 + 16px)`,
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 1104) - 120 - 942) /
															2) +
													0 +
													310 +
													0 +
													432,
											},
											xC_Vf1okp: {
												width: `calc(max((min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1440px) - 16px) / 2, 50px) * 2 + 16px)`,
												y:
													(componentViewport?.y || 0) +
													(80 +
														((componentViewport?.height || 934) - 160 - 942) /
															2) +
													0 +
													310 +
													0 +
													432,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-wx7zam-container"}
										layoutDependency={layoutDependency}
										layoutId={"xksPmED8_-container"}
										nodeId={"xksPmED8_"}
										rendersWithMotion={true}
										scopeId={"lk3otI4uM"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "xksPmED8_",
											layoutId: "xksPmED8_",
											rsZPcYcNG: addImageAlt(
												{
													pixelHeight: 65,
													pixelWidth: 65,
													src: "https://framerusercontent.com/images/TKav1JRKJ38OgJZfI25hYYLug.svg?width=65&height=65",
												},
												"",
											),
											RwK8T9gAW: "Team Communication",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-tpCXd.framer-1lb4a2u, .framer-tpCXd .framer-1lb4a2u { display: block; }",
	".framer-tpCXd.framer-11vlxt1 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 120px 80px 120px 80px; position: relative; width: 1200px; }",
	".framer-tpCXd .framer-1mvp7t0 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-tpCXd .framer-1husmtz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 640px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-tpCXd .framer-1gldzm-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-tpCXd .framer-mx6zsp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-tpCXd .framer-79oxqg, .framer-tpCXd .framer-dacxfe { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-tpCXd .framer-116twm6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-tpCXd .framer-irtgjy-container, .framer-tpCXd .framer-u4urm3-container, .framer-tpCXd .framer-kgck9-container, .framer-tpCXd .framer-xi28ni-container, .framer-tpCXd .framer-wx7zam-container { flex: 1 0 0px; height: 200px; position: relative; width: 1px; }",
	".framer-tpCXd.framer-v-1b5x178.framer-11vlxt1 { padding: 80px 32px 80px 32px; width: 810px; }",
	".framer-tpCXd.framer-v-1b5x178 .framer-116twm6 { align-content: unset; align-items: unset; display: grid; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(2, minmax(0, 1fr)); }",
	".framer-tpCXd.framer-v-1b5x178 .framer-irtgjy-container, .framer-tpCXd.framer-v-xw90qi .framer-irtgjy-container { align-self: start; flex: none; height: 100%; justify-self: start; order: 0; width: 100%; }",
	".framer-tpCXd.framer-v-1b5x178 .framer-u4urm3-container, .framer-tpCXd.framer-v-xw90qi .framer-u4urm3-container { align-self: start; flex: none; height: 100%; justify-self: start; order: 1; width: 100%; }",
	".framer-tpCXd.framer-v-1b5x178 .framer-kgck9-container, .framer-tpCXd.framer-v-xw90qi .framer-kgck9-container { align-self: start; flex: none; height: 100%; justify-self: start; order: 2; width: 100%; }",
	".framer-tpCXd.framer-v-1b5x178 .framer-xi28ni-container, .framer-tpCXd.framer-v-xw90qi .framer-xi28ni-container { align-self: start; flex: none; height: 100%; justify-self: start; order: 3; width: 100%; }",
	".framer-tpCXd.framer-v-1b5x178 .framer-wx7zam-container, .framer-tpCXd.framer-v-xw90qi .framer-wx7zam-container { align-self: start; flex: none; grid-column: span 2; height: 100%; justify-self: start; order: 4; width: 100%; }",
	".framer-tpCXd.framer-v-xw90qi.framer-11vlxt1 { padding: 60px 20px 60px 20px; width: 390px; }",
	".framer-tpCXd.framer-v-xw90qi .framer-1husmtz { order: 0; }",
	".framer-tpCXd.framer-v-xw90qi .framer-116twm6 { align-content: unset; align-items: unset; display: grid; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(3, minmax(0, 1fr)); order: 1; }",
	...css,
	...css2,
];
var Framerlk3otI4uM = withCSS(Component, css3, "framer-tpCXd");
var stdin_default3 = Framerlk3otI4uM;
Framerlk3otI4uM.displayName = "Solutions";
Framerlk3otI4uM.defaultProps = {
	height: 654,
	width: 1200,
};
addPropertyControls(Framerlk3otI4uM, {
	variant: {
		options: ["C3YPHn0db", "xC_Vf1okp", "pNQRoApTa"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerlk3otI4uM,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BadgeMiniFonts,
		...SloutionCardFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:solutions
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "pNQRoApTa",
	md: "xC_Vf1okp",
	xl: "C3YPHn0db",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SolutionsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var solutions_default = ComponentWithRoot;
export { solutions_default as default };
