// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cfe7f02456486a1b "TaskFlow (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-XOCSB6QP.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-XALRBIFG.js";
import { Ticker } from "./chunks/chunk-EKC5TL2T.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-47RE6EUY.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-HZSMZCXU.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SHQ4TVQP.js";
import "./chunks/chunk-U5LHETZW.js";
import { className, css, fonts } from "./chunks/chunk-KO5WDYQX.js";
import { routes } from "./chunks/chunk-UZZEI6KP.js";

// virtual:testimonials
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/n0caVO5quCKZK9jDRMTD/QIHab4kthq6dfhOoa83t/BJ_Yvw04c.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/QidAkIP9cpzCjUSZlY2B/TTluUM03vp6X5HTqvziR/cDfqtRjkj.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-lvhKu";
var variantClassNames = {
	QMRgwKcai: "framer-v-1qomr0l",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	avatar,
	comment,
	height,
	id,
	job,
	name1,
	width,
	...props
}) => {
	return {
		...props,
		csKluY2UM: avatar ??
			props.csKluY2UM ?? {
				src: "https://framerusercontent.com/images/Mb4prylaxDajURFOhVxEDmKPI.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/Mb4prylaxDajURFOhVxEDmKPI.png?scale-down-to=512 512w,https://framerusercontent.com/images/Mb4prylaxDajURFOhVxEDmKPI.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Mb4prylaxDajURFOhVxEDmKPI.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Mb4prylaxDajURFOhVxEDmKPI.png 2400w",
			},
		dhCeo9_Cr:
			comment ??
			props.dhCeo9_Cr ??
			"TaskFlow transformed how our team works. We've cut meeting time in half and doubled our productivity.",
		ijAMoS2uQ: job ?? props.ijAMoS2uQ ?? "Product Manager at Loogle",
		X76PHUvbH: name1 ?? props.X76PHUvbH ?? "Sarah Johnson",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		dhCeo9_Cr,
		csKluY2UM,
		X76PHUvbH,
		ijAMoS2uQ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "QMRgwKcai",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className5, className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1qomr0l",
							className6,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"QMRgwKcai"}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-7e2cee24-41e3-44f2-9710-90e095fcc68d, rgb(229, 231, 235))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-08f2dbd6-30f3-4b80-b3ec-25d8f6146ee9, rgb(255, 255, 255))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-j62w61"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"HlayRb32m"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={dhCeo9_Cr}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1vck8ev"}
									data-styles-preset={"WDjx2gmMn"}
									style={{
										"--framer-text-alignment": "left",
									}}
								>
									{
										"TaskFlow transformed how our team works. We've cut meeting time in half and doubled our productivity."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-f6fv1q"}
							data-framer-name={"Name/Avatar/Status"}
							layoutDependency={layoutDependency}
							layoutId={"lgrxEs7rY"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 32 + 152 + 36,
									),
									sizes: "64px",
									...toResponsiveImage(csKluY2UM),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-8xal8h"}
								data-border={true}
								data-framer-name={"Avatar"}
								layoutDependency={layoutDependency}
								layoutId={"yyWkEk3Ob"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-b63e5580-f724-4b9d-a88b-9db74b9d4550, rgb(156, 163, 175))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 1e3,
									borderBottomRightRadius: 1e3,
									borderTopLeftRadius: 1e3,
									borderTopRightRadius: 1e3,
								}}
							/>
							<motion.div
								className={"framer-1wa4gde"}
								data-framer-name={"Name Status"}
								layoutDependency={layoutDependency}
								layoutId={"uA8DLgxkj"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1rvr64s"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"buvdRXwtD"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={X76PHUvbH}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h5
											className={"framer-styles-preset-q3obf1"}
											data-styles-preset={"O4i2T8vus"}
										>
											{"Sarah Johnson"}
										</motion.h5>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ecbonz"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"yoCWQ0IVL"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={ijAMoS2uQ}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-15l7ucq"}
											data-styles-preset={"C_wsAwEHH"}
										>
											{"Product Manager at Google"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lvhKu.framer-1moxbhp, .framer-lvhKu .framer-1moxbhp { display: block; }",
	".framer-lvhKu.framer-1qomr0l { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 32px; position: relative; width: 607px; will-change: var(--framer-will-change-override, transform); }",
	".framer-lvhKu .framer-j62w61 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 10; }",
	".framer-lvhKu .framer-f6fv1q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 10; }",
	".framer-lvhKu .framer-8xal8h { flex: none; height: 64px; overflow: hidden; position: relative; width: 64px; will-change: var(--framer-will-change-override, transform); }",
	".framer-lvhKu .framer-1wa4gde { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-lvhKu .framer-1rvr64s, .framer-lvhKu .framer-ecbonz { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lvhKu.framer-1qomr0l, .framer-lvhKu .framer-f6fv1q, .framer-lvhKu .framer-1wa4gde { gap: 0px; } .framer-lvhKu.framer-1qomr0l > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-lvhKu.framer-1qomr0l > :first-child, .framer-lvhKu .framer-1wa4gde > :first-child { margin-top: 0px; } .framer-lvhKu.framer-1qomr0l > :last-child, .framer-lvhKu .framer-1wa4gde > :last-child { margin-bottom: 0px; } .framer-lvhKu .framer-f6fv1q > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-lvhKu .framer-f6fv1q > :first-child { margin-left: 0px; } .framer-lvhKu .framer-f6fv1q > :last-child { margin-right: 0px; } .framer-lvhKu .framer-1wa4gde > * { margin: 0px; margin-bottom: calc(6px / 2); margin-top: calc(6px / 2); } }",
	...css5,
	...css2,
	...css,
	'.framer-lvhKu[data-border="true"]::after, .framer-lvhKu [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramercDfqtRjkj = withCSS(Component, css6, "framer-lvhKu");
var stdin_default2 = FramercDfqtRjkj;
FramercDfqtRjkj.displayName = "Testimonial Card";
FramercDfqtRjkj.defaultProps = {
	height: 208,
	width: 607,
};
addPropertyControls(FramercDfqtRjkj, {
	dhCeo9_Cr: {
		defaultValue:
			"TaskFlow transformed how our team works. We've cut meeting time in half and doubled our productivity.",
		displayTextArea: false,
		title: "Comment",
		type: ControlType.String,
	},
	csKluY2UM: {
		__defaultAssetReference:
			"data:framer/asset-reference,Mb4prylaxDajURFOhVxEDmKPI.png?originalFilename=QmQFrzAiH1QTbbz6f38Efq1pHRxHEguHqUCXkU5Lk772NU.png&preferredSize=auto",
		title: "Avatar",
		type: ControlType.ResponsiveImage,
	},
	X76PHUvbH: {
		defaultValue: "Sarah Johnson",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	ijAMoS2uQ: {
		defaultValue: "Product Manager at Loogle",
		displayTextArea: false,
		title: "Job",
		type: ControlType.String,
	},
});
addFonts(
	FramercDfqtRjkj,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/n0caVO5quCKZK9jDRMTD/QIHab4kthq6dfhOoa83t/BJ_Yvw04c.js
var BadgeMiniFonts = getFonts(stdin_default);
var TestimonialCardFonts = getFonts(stdin_default2);
var TickerFonts = getFonts(Ticker);
var cycleOrder = ["S6wgFIPR8", "o9I7u_1_r", "nxs70XChQ"];
var serializationHash2 = "framer-4thUT";
var variantClassNames2 = {
	nxs70XChQ: "framer-v-1vtbv9z",
	o9I7u_1_r: "framer-v-1cw4hsc",
	S6wgFIPR8: "framer-v-1idgdas",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	Desktop: "S6wgFIPR8",
	Phone: "nxs70XChQ",
	Tablet: "o9I7u_1_r",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "S6wgFIPR8",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "S6wgFIPR8",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className3, className4];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1idgdas",
							className6,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"S6wgFIPR8"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-d0b7823d-e074-4a91-a0da-87403f8dd55f, rgb(249, 250, 251))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								nxs70XChQ: {
									"data-framer-name": "Phone",
								},
								o9I7u_1_r: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-w40raj"}
							data-framer-name={"Padding"}
							layoutDependency={layoutDependency}
							layoutId={"dNaA3wNtz"}
						>
							<motion2.div
								className={"framer-1j391mz"}
								data-framer-name={"Head Content"}
								layoutDependency={layoutDependency}
								layoutId={"zNhpuv2z3"}
							>
								<ComponentViewportProvider
									height={28}
									y={
										(componentViewport?.y || 0) +
										(120 +
											((componentViewport?.height || 200) - 240 - 874) / 2) +
										0 +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											nxs70XChQ: {
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 200) - 120 - 894) /
															2) +
													0 +
													0 +
													20 +
													0,
											},
											o9I7u_1_r: {
												y:
													(componentViewport?.y || 0) +
													(80 +
														((componentViewport?.height || 200) - 160 - 874) /
															2) +
													0 +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-bpiutu-container"}
										layoutDependency={layoutDependency}
										layoutId={"oFjV_ahW6-container"}
										nodeId={"oFjV_ahW6"}
										rendersWithMotion={true}
										scopeId={"BJ_Yvw04c"}
									>
										{_jsx2(stdin_default, {
											gQqOpdg6s: "Vélemények",
											height: "100%",
											id: "oFjV_ahW6",
											layoutId: "oFjV_ahW6",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion2.div
									className={"framer-1siu92l"}
									data-framer-name={"Head Text"}
									layoutDependency={layoutDependency}
									layoutId={"QIyMexrBF"}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-d8ti8l"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"RnWUlZVav"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h2
												className={"framer-styles-preset-1owo7gc"}
												data-styles-preset={"IBoZbZL0y"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, rgb(17, 24, 39)))",
												}}
											>
												{"What Our Customers Say"}
											</motion2.h2>
										</React2.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-2h654v"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"NswPqAEtz"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												className={"framer-styles-preset-1f6wsl4"}
												data-styles-preset={"VYWldt3Ia"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-fd483edb-af45-4817-a4ca-cfb10641cc8b, rgb(107, 114, 128)))",
												}}
											>
												{
													"Success stories from teams who transformed their work"
												}
											</motion2.p>
										</React2.Fragment>
									</RichText2>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-1bxtful"}
								data-framer-name={"Testimonial Tikers"}
								layoutDependency={layoutDependency}
								layoutId={"yfRkqefBK"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-vuc70a-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"pFzzyCja0-container"}
										nodeId={"pFzzyCja0"}
										rendersWithMotion={true}
										scopeId={"BJ_Yvw04c"}
									>
										<Ticker
											alignment={"flex-start"}
											direction={"left"}
											fadeOptions={{
												fadeAlpha: 0,
												fadeContent: true,
												fadeInset: 0,
												fadeWidth: 25,
												overflow: false,
											}}
											gap={32}
											height={"100%"}
											hoverFactor={0}
											id={"pFzzyCja0"}
											layoutId={"pFzzyCja0"}
											padding={0}
											paddingBottom={0}
											paddingLeft={0}
											paddingPerSide={false}
											paddingRight={0}
											paddingTop={0}
											sizingOptions={{
												heightType: true,
												widthType: true,
											}}
											slots={[
												<ComponentViewportProvider height={208} width={"385px"}>
													<SmartComponentScopedContainer
														className={"framer-644ns4-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"rDWWGxRYc-rhNHFuLTJ-0-container"}
														nodeId={"rhNHFuLTJ"}
														rendersWithMotion={true}
														scopeId={"BJ_Yvw04c"}
													>
														{_jsx2(stdin_default2, {
															csKluY2UM: addImageAlt(
																{
																	pixelHeight: 1024,
																	pixelWidth: 1024,
																	src: "https://framerusercontent.com/images/7IFOWsHVY0RJFR1n6Chu0jDP1jA.png?width=1024&height=1024",
																	srcSet:
																		"https://framerusercontent.com/images/7IFOWsHVY0RJFR1n6Chu0jDP1jA.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/7IFOWsHVY0RJFR1n6Chu0jDP1jA.png?width=1024&height=1024 1024w",
																},
																"",
															),
															dhCeo9_Cr:
																"TaskFlow increased our team productivity by 40% in just two months. Game-changing platform.",
															height: "100%",
															id: "rhNHFuLTJ",
															ijAMoS2uQ: "CTO at Quantum Dynamics",
															layoutId: "rDWWGxRYc-rhNHFuLTJ-0",
															style: {
																width: "100%",
															},
															width: "100%",
															X76PHUvbH: "Alex Rivera",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider height={208} width={"385px"}>
													<SmartComponentScopedContainer
														className={"framer-cepgti-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"lLl2G4VXd-gspsLxsd3-1-container"}
														nodeId={"gspsLxsd3"}
														rendersWithMotion={true}
														scopeId={"BJ_Yvw04c"}
													>
														{_jsx2(stdin_default2, {
															csKluY2UM: addImageAlt(
																{
																	pixelHeight: 1984,
																	pixelWidth: 2400,
																	src: "https://framerusercontent.com/images/71KKwE26SWa8XLKJlpwnZ7iFLTw.png?width=2400&height=1984",
																	srcSet:
																		"https://framerusercontent.com/images/71KKwE26SWa8XLKJlpwnZ7iFLTw.png?scale-down-to=512&width=2400&height=1984 512w,https://framerusercontent.com/images/71KKwE26SWa8XLKJlpwnZ7iFLTw.png?scale-down-to=1024&width=2400&height=1984 1024w,https://framerusercontent.com/images/71KKwE26SWa8XLKJlpwnZ7iFLTw.png?scale-down-to=2048&width=2400&height=1984 2048w,https://framerusercontent.com/images/71KKwE26SWa8XLKJlpwnZ7iFLTw.png?width=2400&height=1984 2400w",
																},
																"",
															),
															dhCeo9_Cr:
																"Finally found a tool that truly understands remote team collaboration.",
															height: "100%",
															id: "gspsLxsd3",
															ijAMoS2uQ:
																"Operations Head at NeoScale Technologies",
															layoutId: "lLl2G4VXd-gspsLxsd3-1",
															style: {
																width: "100%",
															},
															width: "100%",
															X76PHUvbH: "Sarah Chen",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider height={208} width={"385px"}>
													<SmartComponentScopedContainer
														className={"framer-1po3os2-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"WpXTvqtR3-GJWAdSGTd-2-container"}
														nodeId={"GJWAdSGTd"}
														rendersWithMotion={true}
														scopeId={"BJ_Yvw04c"}
													>
														{_jsx2(stdin_default2, {
															csKluY2UM: addImageAlt(
																{
																	pixelHeight: 1024,
																	pixelWidth: 1024,
																	src: "https://framerusercontent.com/images/4kkJXfh7d6qHmjiQbZTSC4nqJPw.png?width=1024&height=1024",
																	srcSet:
																		"https://framerusercontent.com/images/4kkJXfh7d6qHmjiQbZTSC4nqJPw.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/4kkJXfh7d6qHmjiQbZTSC4nqJPw.png?width=1024&height=1024 1024w",
																},
																"",
															),
															dhCeo9_Cr:
																"Reduced our meeting time by 60% and improved project delivery speed.",
															height: "100%",
															id: "GJWAdSGTd",
															ijAMoS2uQ: "Project Director at Vertex Systems",
															layoutId: "WpXTvqtR3-GJWAdSGTd-2",
															style: {
																width: "100%",
															},
															width: "100%",
															X76PHUvbH: "James Wilson",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider height={208} width={"385px"}>
													<SmartComponentScopedContainer
														className={"framer-a0sqxe-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"fAeXfGU7g-In46TTlA3-3-container"}
														nodeId={"In46TTlA3"}
														rendersWithMotion={true}
														scopeId={"BJ_Yvw04c"}
													>
														{_jsx2(stdin_default2, {
															csKluY2UM: addImageAlt(
																{
																	pixelHeight: 1232,
																	pixelWidth: 928,
																	src: "https://framerusercontent.com/images/J667NnuuzOjOEEYwYWnu9S11cM.png?width=928&height=1232",
																	srcSet:
																		"https://framerusercontent.com/images/J667NnuuzOjOEEYwYWnu9S11cM.png?scale-down-to=1024&width=928&height=1232 771w,https://framerusercontent.com/images/J667NnuuzOjOEEYwYWnu9S11cM.png?width=928&height=1232 928w",
																},
																"",
															),
															dhCeo9_Cr:
																"The automation features save us 15+ hours every week.",
															height: "100%",
															id: "In46TTlA3",
															ijAMoS2uQ: "Engineering Lead at Fusion Analytics",
															layoutId: "fAeXfGU7g-In46TTlA3-3",
															style: {
																width: "100%",
															},
															width: "100%",
															X76PHUvbH: "Maya Patel",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
											]}
											speed={70}
											style={{
												height: "100%",
												width: "100%",
											}}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-19t7abw-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"g8CF0tpGx-container"}
										nodeId={"g8CF0tpGx"}
										rendersWithMotion={true}
										scopeId={"BJ_Yvw04c"}
									>
										<Ticker
											alignment={"flex-start"}
											direction={"right"}
											fadeOptions={{
												fadeAlpha: 0,
												fadeContent: true,
												fadeInset: 0,
												fadeWidth: 26,
												overflow: false,
											}}
											gap={32}
											height={"100%"}
											hoverFactor={0}
											id={"g8CF0tpGx"}
											layoutId={"g8CF0tpGx"}
											padding={0}
											paddingBottom={0}
											paddingLeft={0}
											paddingPerSide={false}
											paddingRight={0}
											paddingTop={0}
											sizingOptions={{
												heightType: true,
												widthType: true,
											}}
											slots={[
												<ComponentViewportProvider height={208} width={"385px"}>
													<SmartComponentScopedContainer
														className={"framer-4ai7do-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"qgedcxIhH-fWmElQDR3-0-container"}
														nodeId={"fWmElQDR3"}
														rendersWithMotion={true}
														scopeId={"BJ_Yvw04c"}
													>
														{_jsx2(stdin_default2, {
															dhCeo9_Cr:
																"TaskFlow transformed how our team works. We've cut meeting time in half and doubled our productivity.",
															height: "100%",
															id: "fWmElQDR3",
															ijAMoS2uQ: "Product Manager at Loogle",
															layoutId: "qgedcxIhH-fWmElQDR3-0",
															style: {
																width: "100%",
															},
															width: "100%",
															X76PHUvbH: "Sarah Johnson",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider height={208} width={"385px"}>
													<SmartComponentScopedContainer
														className={"framer-17ym0oh-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"E2ZtnfZ7o-hGXRTltTB-1-container"}
														nodeId={"hGXRTltTB"}
														rendersWithMotion={true}
														scopeId={"BJ_Yvw04c"}
													>
														{_jsx2(stdin_default2, {
															csKluY2UM: addImageAlt(
																{
																	pixelHeight: 1024,
																	pixelWidth: 1024,
																	src: "https://framerusercontent.com/images/6p0K4BG0y8jSDWlpHKDhpBCHZAE.png?width=1024&height=1024",
																	srcSet:
																		"https://framerusercontent.com/images/6p0K4BG0y8jSDWlpHKDhpBCHZAE.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/6p0K4BG0y8jSDWlpHKDhpBCHZAE.png?width=1024&height=1024 1024w",
																},
																"",
															),
															dhCeo9_Cr:
																"Perfect balance of simplicity and powerful features. Worth every penny.",
															height: "100%",
															id: "hGXRTltTB",
															ijAMoS2uQ: "CEO at BlueShift Solutions",
															layoutId: "E2ZtnfZ7o-hGXRTltTB-1",
															style: {
																width: "100%",
															},
															width: "100%",
															X76PHUvbH: "Tom Anderson",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider height={208} width={"385px"}>
													<SmartComponentScopedContainer
														className={"framer-daryby-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"foXLGRMQX-pUWB8IDaC-2-container"}
														nodeId={"pUWB8IDaC"}
														rendersWithMotion={true}
														scopeId={"BJ_Yvw04c"}
													>
														{_jsx2(stdin_default2, {
															csKluY2UM: addImageAlt(
																{
																	pixelHeight: 2464,
																	pixelWidth: 1856,
																	src: "https://framerusercontent.com/images/AQE0ulaHKpFhKZfUDkFwEsw85pk.png?width=1856&height=2464",
																	srcSet:
																		"https://framerusercontent.com/images/AQE0ulaHKpFhKZfUDkFwEsw85pk.png?scale-down-to=1024&width=1856&height=2464 771w,https://framerusercontent.com/images/AQE0ulaHKpFhKZfUDkFwEsw85pk.png?scale-down-to=2048&width=1856&height=2464 1542w,https://framerusercontent.com/images/AQE0ulaHKpFhKZfUDkFwEsw85pk.png?width=1856&height=2464 1856w",
																},
																"",
															),
															dhCeo9_Cr:
																"Switched from 3 different tools to just TaskFlow. Best decision ever.",
															height: "100%",
															id: "pUWB8IDaC",
															ijAMoS2uQ: "Product Manager at Aurora Tech",
															layoutId: "foXLGRMQX-pUWB8IDaC-2",
															style: {
																width: "100%",
															},
															width: "100%",
															X76PHUvbH: "Lisa Zhang",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider height={208} width={"385px"}>
													<SmartComponentScopedContainer
														className={"framer-cejvnp-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"jEWKei7ga-J5XavFj7o-3-container"}
														nodeId={"J5XavFj7o"}
														rendersWithMotion={true}
														scopeId={"BJ_Yvw04c"}
													>
														{_jsx2(stdin_default2, {
															csKluY2UM: addImageAlt(
																{
																	pixelHeight: 2912,
																	pixelWidth: 1632,
																	src: "https://framerusercontent.com/images/gqRmfHJk0MicoM2DVcgM9FBA2E.png?width=1632&height=2912",
																	srcSet:
																		"https://framerusercontent.com/images/gqRmfHJk0MicoM2DVcgM9FBA2E.png?scale-down-to=1024&width=1632&height=2912 573w,https://framerusercontent.com/images/gqRmfHJk0MicoM2DVcgM9FBA2E.png?scale-down-to=2048&width=1632&height=2912 1147w,https://framerusercontent.com/images/gqRmfHJk0MicoM2DVcgM9FBA2E.png?width=1632&height=2912 1632w",
																},
																"",
															),
															dhCeo9_Cr:
																"TaskFlow's templates cut our onboarding time in half.",
															height: "100%",
															id: "J5XavFj7o",
															ijAMoS2uQ: "HR Director at Catalyst Industries",
															layoutId: "jEWKei7ga-J5XavFj7o-3",
															style: {
																width: "100%",
															},
															width: "100%",
															X76PHUvbH: "David Kim",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
											]}
											speed={70}
											style={{
												height: "100%",
												width: "100%",
											}}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-4thUT.framer-1p1kqiv, .framer-4thUT .framer-1p1kqiv { display: block; }",
	".framer-4thUT.framer-1idgdas { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 120px 80px 120px 80px; position: relative; width: 1200px; }",
	".framer-4thUT .framer-w40raj { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-4thUT .framer-1j391mz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 640px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-4thUT .framer-bpiutu-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-4thUT .framer-1siu92l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-4thUT .framer-d8ti8l, .framer-4thUT .framer-2h654v { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-4thUT .framer-1bxtful { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-4thUT .framer-vuc70a-container, .framer-4thUT .framer-19t7abw-container { flex: none; height: 270px; position: relative; width: 100%; }",
	".framer-4thUT .framer-644ns4-container, .framer-4thUT .framer-cepgti-container, .framer-4thUT .framer-1po3os2-container, .framer-4thUT .framer-a0sqxe-container, .framer-4thUT .framer-4ai7do-container, .framer-4thUT .framer-17ym0oh-container, .framer-4thUT .framer-daryby-container, .framer-4thUT .framer-cejvnp-container { height: auto; position: relative; width: 385px; }",
	".framer-4thUT.framer-v-1cw4hsc.framer-1idgdas { padding: 80px 32px 80px 32px; width: 810px; }",
	".framer-4thUT.framer-v-1vtbv9z.framer-1idgdas { padding: 60px 0px 60px 0px; width: 390px; }",
	".framer-4thUT.framer-v-1vtbv9z .framer-w40raj { gap: 60px; }",
	".framer-4thUT.framer-v-1vtbv9z .framer-1j391mz { order: 0; padding: 20px; }",
	".framer-4thUT.framer-v-1vtbv9z .framer-1bxtful { order: 1; }",
	...css3,
	...css4,
];
var FramerBJ_Yvw04c = withCSS2(Component2, css7, "framer-4thUT");
var stdin_default3 = FramerBJ_Yvw04c;
FramerBJ_Yvw04c.displayName = "Testimonials";
FramerBJ_Yvw04c.defaultProps = {
	height: 1018,
	width: 1200,
};
addPropertyControls2(FramerBJ_Yvw04c, {
	variant: {
		options: ["S6wgFIPR8", "o9I7u_1_r", "nxs70XChQ"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerBJ_Yvw04c,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BadgeMiniFonts,
		...TestimonialCardFonts,
		...TickerFonts,
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonials
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "nxs70XChQ",
	md: "o9I7u_1_r",
	xl: "S6wgFIPR8",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var testimonials_default = ComponentWithRoot;
export { testimonials_default as default };
