// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cfe7f02456486a1b "TaskFlow (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-UDRHTIWX.js";
import { className, css, fonts } from "./chunks/chunk-7QNJWUDS.js";
import { stdin_default } from "./chunks/chunk-5AST346G.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-EGCCNRVP.js";
import "./chunks/chunk-6X4H3KEO.js";
import "./chunks/chunk-U5LHETZW.js";
import { routes } from "./chunks/chunk-UZZEI6KP.js";

// virtual:video-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/MVdvSfcajsgLjTAfxqi6/TGAPZr6Ti68M4BSmkMxZ/OirQ4EhuU.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType5,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/NEd4VmDdsxM3StIUbddO/4sbLnuatuUfmOTwFGSJM/YouTube.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import { useReducer, useState as useState3 } from "react";
import { ControlType as ControlType4, addPropertyControls } from "unframer";

// /:https://framerusercontent.com/modules/VTUDdizacRHpwbkOamr7/AykinQJbgwl92LvMGZwu/constants.js
import { ControlType } from "unframer";
var containerStyles = {
	position: "relative",
	width: "100%",
	height: "100%",
	display: "flex",
	justifyContent: "center",
	alignItems: "center",
};
var emptyStateStyle = {
	...containerStyles,
	borderRadius: 6,
	background: "rgba(136, 85, 255, 0.3)",
	color: "#85F",
	border: "1px dashed #85F",
	flexDirection: "column",
};
var defaultEvents = {
	onClick: {
		type: ControlType.EventHandler,
	},
	onMouseEnter: {
		type: ControlType.EventHandler,
	},
	onMouseLeave: {
		type: ControlType.EventHandler,
	},
};
var fontSizeOptions = {
	type: ControlType.Number,
	title: "Font Size",
	min: 2,
	max: 200,
	step: 1,
	displayStepper: true,
};
var fontControls = {
	font: {
		type: ControlType.Boolean,
		title: "Font",
		defaultValue: false,
		disabledTitle: "Default",
		enabledTitle: "Custom",
	},
	fontFamily: {
		type: ControlType.String,
		title: "Family",
		placeholder: "Inter",
		hidden: ({ font }) => !font,
	},
	fontWeight: {
		type: ControlType.Enum,
		title: "Weight",
		options: [100, 200, 300, 400, 500, 600, 700, 800, 900],
		optionTitles: [
			"Thin",
			"Extra-light",
			"Light",
			"Regular",
			"Medium",
			"Semi-bold",
			"Bold",
			"Extra-bold",
			"Black",
		],
		hidden: ({ font }) => !font,
	},
};

// /:https://framerusercontent.com/modules/D4TWeLfcxT6Tysr2BlYg/iZjmqdxVx1EOiM3k1FaW/useOnNavigationTargetChange.js
import { useIsInCurrentNavigationTarget } from "unframer";
import { useEffect } from "react";

// /:https://framerusercontent.com/modules/ExNgrA7EJTKUPpH6vIlN/eiOrSJ2Ab5M9jPCvVwUz/useConstant.js
import { useRef } from "react";

// /:https://framerusercontent.com/modules/D2Lz5CmnNVPZFFiZXalt/QaCzPbriZBfXWZIIycFI/colorFromToken.js
import { Color } from "unframer";

// /:https://framerusercontent.com/modules/3mKFSGQqKHV82uOV1eBc/5fbRLvOpxZC0JOXugvwm/isMotionValue.js
import { MotionValue } from "unframer";

// /:https://framerusercontent.com/modules/xDiQsqBGXzmMsv7AlEVy/uhunpMiNsbXxzjlXsg1y/useUniqueClassName.js
import * as React from "react";

// /:https://framerusercontent.com/modules/ETACN5BJyFTSo0VVDJfu/NHRqowOiXkF9UwOzczF7/variantUtils.js
import { ControlType as ControlType2 } from "unframer";

// /:https://framerusercontent.com/modules/eMBrwoqQK7h6mEeGQUH8/GuplvPJVjmxpk9zqOTcb/isBrowser.js
import { useMemo } from "react";

// /:https://framerusercontent.com/modules/v9AWX2URmiYsHf7GbctE/XxKAZ9KlhWqf5x1JMyyF/useOnChange.js
import { useEffect as useEffect3 } from "react";

// /:https://framerusercontent.com/modules/kNDwabfjDEb3vUxkQlZS/fSIr3AOAYbGlfSPgXpYu/useAutoMotionValue.js
import { useCallback, useEffect as useEffect4, useRef as useRef2 } from "react";
import { motionValue, animate, RenderTarget } from "unframer";

// /:https://framerusercontent.com/modules/cuQH4dmpDnV8YK1mSgQX/KqRXqunFjE6ufhpc7ZRu/useFontControls.js
import { fontStore } from "unframer";
import { useEffect as useEffect5 } from "react";

// /:https://framerusercontent.com/modules/afBE9Yx1W6bY5q32qPxe/m3q7puE2tbo1S2C0s0CT/useRenderTarget.js
import { useMemo as useMemo2 } from "react";
import { RenderTarget as RenderTarget2 } from "unframer";
function useIsOnCanvas() {
	const onCanvas = useMemo2(
		() => RenderTarget2.current() === RenderTarget2.canvas,
		[],
	);
	return onCanvas;
}

// /:https://framerusercontent.com/modules/zGkoP8tPDCkoBzMdt5uq/0zFSjxIYliHxrQQnryFX/useControlledState.js
import * as React2 from "react";

// /:https://framerusercontent.com/modules/5SM58HxZHxjjv7aLMOgQ/WXz9i6mVki0bBCrKdqB3/propUtils.js
import { useMemo as useMemo3 } from "react";
import { ControlType as ControlType3 } from "unframer";
function useRadius(props) {
	const {
		borderRadius,
		isMixedBorderRadius,
		topLeftRadius,
		topRightRadius,
		bottomRightRadius,
		bottomLeftRadius,
	} = props;
	const radiusValue = useMemo3(
		() =>
			isMixedBorderRadius
				? `${topLeftRadius}px ${topRightRadius}px ${bottomRightRadius}px ${bottomLeftRadius}px`
				: `${borderRadius}px`,
		[
			borderRadius,
			isMixedBorderRadius,
			topLeftRadius,
			topRightRadius,
			bottomRightRadius,
			bottomLeftRadius,
		],
	);
	return radiusValue;
}
var borderRadiusControl = {
	borderRadius: {
		title: "Radius",
		type: ControlType3.FusedNumber,
		toggleKey: "isMixedBorderRadius",
		toggleTitles: ["Radius", "Radius per corner"],
		valueKeys: [
			"topLeftRadius",
			"topRightRadius",
			"bottomRightRadius",
			"bottomLeftRadius",
		],
		valueLabels: ["TL", "TR", "BR", "BL"],
		min: 0,
	},
};
var paddingControl = {
	padding: {
		type: ControlType3.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
		title: "Padding",
	},
};

// /:https://framerusercontent.com/modules/NEd4VmDdsxM3StIUbddO/4sbLnuatuUfmOTwFGSJM/YouTube.js
var PlayOptions;
(function (PlayOptions2) {
	PlayOptions2["Normal"] = "Off";
	PlayOptions2["Auto"] = "On";
	PlayOptions2["Loop"] = "Loop";
})(PlayOptions || (PlayOptions = {}));
var ThumbnailOptions;
(function (ThumbnailOptions2) {
	ThumbnailOptions2["High"] = "High Quality";
	ThumbnailOptions2["Medium"] = "Medium Quality";
	ThumbnailOptions2["Low"] = "Low Quality";
	ThumbnailOptions2["Off"] = "Off";
})(ThumbnailOptions || (ThumbnailOptions = {}));
function Youtube({
	url,
	play,
	shouldMute,
	thumbnail,
	isRed,
	onClick,
	onMouseEnter,
	onMouseLeave,
	onMouseDown,
	onMouseUp,
	title,
	...props
}) {
	const onCanvas = useIsOnCanvas();
	const isAutoplay = play !== "Off";
	const showThumbnail = onCanvas || (thumbnail !== "Off" && !isAutoplay);
	const [isPreloading, preloadVideo] = useReducer(() => true, false);
	const [showVideo, startVideo] = useReducer(() => true, !showThumbnail);
	const [isHovered, setHovered] = useState3(false);
	const borderRadius = useRadius(props);
	const hasBorderRadius =
		borderRadius !== "0px 0px 0px 0px" && borderRadius !== "0px";
	if (url === "") {
		return <Instructions />;
	}
	const parsedURL = parseVideoURL(url);
	if (parsedURL === void 0) {
		return <ErrorMessage message={"Invalid Youtube URL."} />;
	}
	const [videoId, embedURL, originalSearchParams] = parsedURL;
	const searchParams = embedURL.searchParams;
	if (originalSearchParams) {
		for (const [param, value] of originalSearchParams) {
			searchParams.set(param, value);
			if (param === "t") searchParams.set("start", value);
		}
	}
	searchParams.set("iv_load_policy", "3");
	searchParams.set("rel", "0");
	searchParams.set("modestbranding", "1");
	searchParams.set("playsinline", "1");
	if (!showVideo) {
		searchParams.set("autoplay", "0");
	} else if (
		isAutoplay ||
		// when there is no thumbnail, we don't want to autoplay, unless video is started
		(showThumbnail && showVideo)
	) {
		searchParams.set("autoplay", "1");
	}
	if (isAutoplay && shouldMute) {
		searchParams.set("mute", "1");
	}
	if (play === "Loop") {
		searchParams.set("loop", "1");
		searchParams.set("playlist", videoId);
	}
	if (!isRed) {
		searchParams.set("color", "white");
	}
	const iframeProps = {
		title: title || "Youtube Video",
		allow:
			"presentation; fullscreen; accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture",
		src: embedURL.href,
		frameBorder: "0",
		onClick,
		onMouseEnter,
		onMouseLeave,
		onMouseDown,
		onMouseUp,
	};
	return (
		<article
			onPointerEnter={() => setHovered(true)}
			onPointerLeave={() => setHovered(false)}
			onPointerOver={preloadVideo}
			onKeyDown={startVideo}
			onClick={startVideo}
			style={{
				...wrapperStyle,
				borderRadius,
				transform:
					// Safari sometimes struggles to render border-radius:
					// - on the canvas when changing from 0 to any other value
					// - or when rendering an iframe
					hasBorderRadius && (showVideo || onCanvas)
						? "translateZ(0.000001px)"
						: "unset",
				cursor: "pointer",
				overflow: "hidden",
			}}
			role={"presentation"}
		>
			{isPreloading && (
				<link rel={"preconnect"} href={"https://www.youtube.com"} />
			)}
			{isPreloading && (
				<link rel={"preconnect"} href={"https://www.google.com"} />
			)}
			{showThumbnail && (
				<_Fragment>
					<link rel={"preconnect"} href={"https://i.ytimg.com"} />
					<img
						decoding={"async"}
						src={getThumbnailURL(videoId, thumbnail)}
						style={{
							...videoStyle,
							objectFit: "cover",
						}}
					/>
				</_Fragment>
			)}
			{!onCanvas ? (
				<iframe
					loading={!showVideo ? "lazy" : void 0}
					style={
						!showVideo
							? {
									...videoStyle,
									display: "none",
								}
							: videoStyle
					}
					{...iframeProps}
				/>
			) : null}
			{showVideo ? null : (
				<PlayButton onClick={startVideo} isHovered={isHovered} isRed={isRed} />
			)}
		</article>
	);
}
Youtube.displayName = "YouTube";
addPropertyControls(Youtube, {
	url: {
		type: ControlType4.String,
		title: "Video",
	},
	play: {
		type: ControlType4.Enum,
		title: "Autoplay",
		options: Object.values(PlayOptions),
	},
	shouldMute: {
		title: "Mute",
		type: ControlType4.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		hidden(props) {
			return props.play === "Off";
		},
	},
	thumbnail: {
		title: "Thumbnail",
		description: "Showing a thumbnail improves performance.",
		type: ControlType4.Enum,
		options: Object.values(ThumbnailOptions),
		hidden(props) {
			return props.play !== "Off";
		},
	},
	isRed: {
		title: "Color",
		type: ControlType4.Boolean,
		enabledTitle: "Red",
		disabledTitle: "White",
	},
	...borderRadiusControl,
	...defaultEvents,
});
var defaultProps = {
	url: "https://youtu.be/8AHPXm9Y6mI",
	play: "Off",
	shouldMute: true,
	thumbnail: "Medium Quality",
	isRed: true,
};
Youtube.defaultProps = defaultProps;
function parseVideoURL(urlString) {
	let url;
	try {
		url = new URL(urlString);
	} catch {
		const embedURL = getEmbedURL(urlString);
		return [urlString, embedURL, null];
	}
	const searchParams = url.searchParams;
	if (
		url.hostname === "youtube.com" ||
		url.hostname === "www.youtube.com" ||
		url.hostname === "youtube-nocookie.com" ||
		url.hostname === "www.youtube-nocookie.com"
	) {
		const pathSegments = url.pathname.slice(1).split("/");
		const page = pathSegments[0];
		if (page === "watch") {
			const videoId = url.searchParams.get("v");
			const embedURL = getEmbedURL(videoId);
			return [videoId, embedURL, searchParams];
		}
		if (page === "embed") {
			const videoId = pathSegments[1];
			return [videoId, url, searchParams];
		}
		if (page === "shorts" || page === "live") {
			const videoId = pathSegments[1];
			const embedURL = getEmbedURL(videoId);
			return [videoId, embedURL, searchParams];
		}
	}
	if (url.hostname === "youtu.be") {
		const videoId = url.pathname.slice(1);
		const embedURL = getEmbedURL(videoId);
		return [videoId, embedURL, searchParams];
	}
}
function getEmbedURL(videoId) {
	return new URL(`https://www.youtube.com/embed/${videoId}`);
}
function getThumbnailURL(videoId, res) {
	const pre = "https://i.ytimg.com/vi_webp/";
	const ext = "webp";
	switch (res) {
		case "Low Quality":
			return `${pre}${videoId}/hqdefault.${ext}`;
		case "Medium Quality":
			return `${pre}${videoId}/sddefault.${ext}`;
		case "High Quality":
			return `${pre}${videoId}/maxresdefault.${ext}`;
		default:
			return `${pre}${videoId}/0.${ext}`;
	}
}
function Instructions() {
	return (
		<div
			style={{
				...emptyStateStyle,
				overflow: "hidden",
			}}
		>
			<div style={centerTextStyle}>
				{"To embed a Youtube video, add the URL to the properties\xA0panel."}
			</div>
		</div>
	);
}
function ErrorMessage({ message }) {
	return (
		<div
			className={"framerInternalUI-errorPlaceholder"}
			style={{
				...containerStyles,
				overflow: "hidden",
			}}
		>
			<div style={centerTextStyle}>
				{"Error: "}
				{message}
			</div>
		</div>
	);
}
function PlayButton({ onClick, isHovered, isRed }) {
	return (
		<button onClick={onClick} aria-label={"Play"} style={buttonStyle}>
			<svg height={"100%"} version={"1.1"} viewBox={"0 0 68 48"} width={"100%"}>
				<path
					d={
						"M66.52,7.74c-0.78-2.93-2.49-5.41-5.42-6.19C55.79,.13,34,0,34,0S12.21,.13,6.9,1.55 C3.97,2.33,2.27,4.81,1.48,7.74C0.06,13.05,0,24,0,24s0.06,10.95,1.48,16.26c0.78,2.93,2.49,5.41,5.42,6.19 C12.21,47.87,34,48,34,48s21.79-0.13,27.1-1.55c2.93-0.78,4.64-3.26,5.42-6.19C67.94,34.95,68,24,68,24S67.94,13.05,66.52,7.74z"
					}
					fill={isHovered ? (isRed ? "#f00" : "#000") : "#212121"}
					fillOpacity={isHovered ? (isRed ? 1 : 0.8) : 0.8}
					style={{
						transition:
							"fill .1s cubic-bezier(0.4, 0, 1, 1), fill-opacity .1s cubic-bezier(0.4, 0, 1, 1)",
					}}
				/>
				<path d={"M 45,24 27,14 27,34"} fill={"#fff"} />
			</svg>
		</button>
	);
}
var buttonStyle = {
	position: "absolute",
	top: "50%",
	left: "50%",
	transform: "translate(-50%, -50%)",
	width: 68,
	height: 48,
	padding: 0,
	border: "none",
	background: "transparent",
	cursor: "pointer",
};
var wrapperStyle = {
	position: "relative",
	width: "100%",
	height: "100%",
};
var centerTextStyle = {
	textAlign: "center",
	minWidth: 140,
};
var videoStyle = {
	position: "absolute",
	top: 0,
	left: 0,
	height: "100%",
	width: "100%",
};

// /:https://framerusercontent.com/modules/gsreJCk3pefWz5oFuvWP/hEumhti6BkzuKnRaFgi8/C_wsAwEHH.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	`.framer-1h8h0 .framer-styles-preset-15l7ucq:not(.rich-text-wrapper), .framer-1h8h0 .framer-styles-preset-15l7ucq.rich-text-wrapper p { --framer-font-family: "Inter", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 22px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #666666; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className3 = "framer-1h8h0";

// /:https://framerusercontent.com/modules/mLeIzvvMZjEyPMCknLPY/wMjUx0EIrzDVOD4s4Six/wJUNQa8c4.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts([
	"Inter-Bold",
	"Inter-Black",
	"Inter-BlackItalic",
	"Inter-BoldItalic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/mkY5Sgyq51ik0AMrSBwhm9DJg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/X5hj6qzcHUYv7h1390c8Rhm6550.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/gQhNpS3tN86g8RcVKYUUaKt2oMQ.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cugnVhSraaRyANCaUtI5FV17wk.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/5HcVoGak8k5agFJSaKa4floXVu0.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/jn4BtSPLlS0NDp1KiFAtFKiiY0o.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/P2Bw01CtL0b9wqygO0sSVogWbo.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/05KsVHGDmqXSBXM4yRZ65P8i0s.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/ky8ovPukK4dJ1Pxq74qGhOqCYI.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/vvNSqIj42qeQ2bvCRBIWKHscrc.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/3ZmXbBKToJifDV9gwcifVd1tEY.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/FNfhX3dt4ChuLJq2PwdlxHO7PU.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/g0c8vEViiXNlKAgI4Ymmk3Ig.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/efTfQcBJ53kM2pB1hezSZ3RDUFs.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
		],
	},
];
var css4 = [
	'.framer-3hb43 .framer-styles-preset-fcvc2w:not(.rich-text-wrapper), .framer-3hb43 .framer-styles-preset-fcvc2w.rich-text-wrapper h4 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.01em; --framer-line-height: 24px; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, #111827); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-3hb43 .framer-styles-preset-fcvc2w:not(.rich-text-wrapper), .framer-3hb43 .framer-styles-preset-fcvc2w.rich-text-wrapper h4 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.01em; --framer-line-height: 22px; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, #111827); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-3hb43 .framer-styles-preset-fcvc2w:not(.rich-text-wrapper), .framer-3hb43 .framer-styles-preset-fcvc2w.rich-text-wrapper h4 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.01em; --framer-line-height: 20px; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-05a7cdfd-1e0f-43da-a9f6-b4623556492c, #111827); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className4 = "framer-3hb43";

// /:https://framerusercontent.com/modules/MVdvSfcajsgLjTAfxqi6/TGAPZr6Ti68M4BSmkMxZ/OirQ4EhuU.js
var BadgeMiniFonts = getFonts(stdin_default);
var ButtonSecondaryFonts = getFonts(stdin_default2);
var YouTubeFonts = getFonts(Youtube);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["d9XwXt7BX", "HO0uYnuA6", "O29eogJzE"];
var serializationHash = "framer-ATnNt";
var variantClassNames = {
	d9XwXt7BX: "framer-v-1hmdq4z",
	HO0uYnuA6: "framer-v-15bd0no",
	O29eogJzE: "framer-v-109gjyv",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 35,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React3.Fragment);
var humanReadableVariantMap = {
	Desktop: "d9XwXt7BX",
	Phone: "O29eogJzE",
	Tablet: "HO0uYnuA6",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "d9XwXt7BX",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "d9XwXt7BX",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2, className4, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1hmdq4z",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"d9XwXt7BX"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-08f2dbd6-30f3-4b80-b3ec-25d8f6146ee9, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								HO0uYnuA6: {
									"data-framer-name": "Tablet",
								},
								O29eogJzE: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1a022rf"}
							data-framer-name={"Padding"}
							layoutDependency={layoutDependency}
							layoutId={"jwgpSjhnp"}
						>
							<motion.div
								className={"framer-ydck4n"}
								data-framer-name={"Padding"}
								layoutDependency={layoutDependency}
								layoutId={"CuTb8__hY"}
							>
								<ComponentViewportProvider
									height={28}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 200) - 160 - 1211) / 2 +
											0 +
											0) +
										0 +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											O29eogJzE: {
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 200) - 160 - 1659) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-90p3pk-container"}
										layoutDependency={layoutDependency}
										layoutId={"a8_yYDPZZ-container"}
										nodeId={"a8_yYDPZZ"}
										rendersWithMotion={true}
										scopeId={"OirQ4EhuU"}
									>
										{_jsx2(stdin_default, {
											gQqOpdg6s: "Video",
											height: "100%",
											id: "a8_yYDPZZ",
											layoutId: "a8_yYDPZZ",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ev7frk"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"NsnSNLpZc"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion.h2
											className={"framer-styles-preset-1owo7gc"}
											data-styles-preset={"IBoZbZL0y"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"See TaskFlow in Action"}
										</motion.h2>
									</React3.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-l5vdfc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"P065IFpki"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion.p
											className={"framer-styles-preset-1f6wsl4"}
											data-styles-preset={"VYWldt3Ia"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{
												"Watch how TaskFlow transforms team collaboration and project management in just 2 minutes"
											}
										</motion.p>
									</React3.Fragment>
								</RichText>
								<ComponentViewportProvider
									height={40}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 200) - 160 - 1211) / 2 +
											0 +
											0) +
										0 +
										0 +
										0 +
										262
									}
									{...addPropertyOverrides(
										{
											O29eogJzE: {
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 200) - 160 - 1659) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													262,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-yg1jta-container"}
										layoutDependency={layoutDependency}
										layoutId={"sZgKFVDSM-container"}
										nodeId={"sZgKFVDSM"}
										rendersWithMotion={true}
										scopeId={"OirQ4EhuU"}
									>
										{_jsx2(stdin_default2, {
											bL9DUTLS5: "Get Started",
											height: "100%",
											id: "sZgKFVDSM",
											kI0zFLUtw: "https://framer.com/r/signup",
											layoutId: "sZgKFVDSM",
											style: {
												height: "100%",
											},
											variant: "H2RtDWI43",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<motion.div
								className={"framer-1ug5mqs"}
								data-border={true}
								data-framer-name={"Video"}
								layoutDependency={layoutDependency}
								layoutId={"MuH97bidW"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-7e2cee24-41e3-44f2-9710-90e095fcc68d, rgb(229, 231, 235))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor:
										"var(--token-08f2dbd6-30f3-4b80-b3ec-25d8f6146ee9, rgb(255, 255, 255))",
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
									boxShadow:
										"0px 1.0780770778656006px 2.261847972869873px 0px rgba(45, 48, 57, 0.03), 0px 2.590769052505493px 5.435535430908203px 0px rgba(45, 48, 57, 0.04), 0px 4.878188610076904px 10.234630584716797px 0px rgba(45, 48, 57, 0.05), 0px 8.701854705810547px 18.256832122802734px 0px rgba(45, 48, 57, 0.05), 0px 16.275861740112305px 34.147396087646484px 0px rgba(45, 48, 57, 0.06), 0px 38.958335876464844px 81.73611450195312px 0px rgba(45, 48, 57, 0.09)",
								}}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-1he4jel-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"JxNlTOH74-container"}
										nodeId={"JxNlTOH74"}
										rendersWithMotion={true}
										scopeId={"OirQ4EhuU"}
									>
										<Youtube
											borderRadius={8}
											bottomLeftRadius={8}
											bottomRightRadius={8}
											height={"100%"}
											id={"JxNlTOH74"}
											isMixedBorderRadius={false}
											isRed={true}
											layoutId={"JxNlTOH74"}
											play={"Off"}
											shouldMute={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											thumbnail={"High Quality"}
											topLeftRadius={8}
											topRightRadius={8}
											url={
												"https://www.youtube.com/watch?v=UpQYw2aq0po&ab_channel=Framer"
											}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<motion.div
								className={"framer-2pn2o8"}
								data-framer-name={"Features Text"}
								layoutDependency={layoutDependency}
								layoutId={"qo3qi71l1"}
							>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition1,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1i4qadq"}
									layoutDependency={layoutDependency}
									layoutId={"lLYVHfjxx"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1ochhya"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ogkkyQOBV"}
										style={{
											"--extracted-1eung3n":
												"var(--token-70ee1060-3c83-4aa7-a752-6352a72d1a9b, rgb(59, 130, 246))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion.h4
												className={"framer-styles-preset-fcvc2w"}
												data-styles-preset={"wJUNQa8c4"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-70ee1060-3c83-4aa7-a752-6352a72d1a9b, rgb(59, 130, 246)))",
												}}
											>
												{"Smart Workspaces"}
											</motion.h4>
										</React3.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1d8prri"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"k8X2ptSHe"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion.p
												className={"framer-styles-preset-15l7ucq"}
												data-styles-preset={"C_wsAwEHH"}
												style={{
													"--framer-text-alignment": "center",
												}}
											>
												{"See how our AI-powered templates boost productivity"}
											</motion.p>
										</React3.Fragment>
									</RichText>
								</MotionDivWithFX>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition1,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1n3jcqh"}
									layoutDependency={layoutDependency}
									layoutId={"vdCVcBtXK"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1b119ih"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Jlk6Qz2VC"}
										style={{
											"--extracted-1eung3n":
												"var(--token-70ee1060-3c83-4aa7-a752-6352a72d1a9b, rgb(59, 130, 246))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion.h4
												className={"framer-styles-preset-fcvc2w"}
												data-styles-preset={"wJUNQa8c4"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-70ee1060-3c83-4aa7-a752-6352a72d1a9b, rgb(59, 130, 246)))",
												}}
											>
												{"Real-time Collaboration"}
											</motion.h4>
										</React3.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-wxueil"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"pWtX57Ykl"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion.p
												className={"framer-styles-preset-15l7ucq"}
												data-styles-preset={"C_wsAwEHH"}
												style={{
													"--framer-text-alignment": "center",
												}}
											>
												{"Watch teams work together seamlessly from anywhere"}
											</motion.p>
										</React3.Fragment>
									</RichText>
								</MotionDivWithFX>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition1,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1rx4fuj"}
									layoutDependency={layoutDependency}
									layoutId={"CCRC2AVLM"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1uksdtr"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"qHETgB_z6"}
										style={{
											"--extracted-1eung3n":
												"var(--token-70ee1060-3c83-4aa7-a752-6352a72d1a9b, rgb(59, 130, 246))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion.h4
												className={"framer-styles-preset-fcvc2w"}
												data-styles-preset={"wJUNQa8c4"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-70ee1060-3c83-4aa7-a752-6352a72d1a9b, rgb(59, 130, 246)))",
												}}
											>
												{"Automated Workflows"}
											</motion.h4>
										</React3.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1aw1zwu"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"hBPiwI3zM"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion.p
												className={"framer-styles-preset-15l7ucq"}
												data-styles-preset={"C_wsAwEHH"}
												style={{
													"--framer-text-alignment": "center",
												}}
											>
												{"Discover how automation saves your team time"}
											</motion.p>
										</React3.Fragment>
									</RichText>
								</MotionDivWithFX>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ATnNt.framer-9cfvkq, .framer-ATnNt .framer-9cfvkq { display: block; }",
	".framer-ATnNt.framer-1hmdq4z { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: visible; padding: 80px; position: relative; width: 1200px; }",
	".framer-ATnNt .framer-1a022rf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ATnNt .framer-ydck4n { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 640px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ATnNt .framer-90p3pk-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-ATnNt .framer-ev7frk, .framer-ATnNt .framer-l5vdfc, .framer-ATnNt .framer-1ochhya, .framer-ATnNt .framer-1d8prri, .framer-ATnNt .framer-1b119ih, .framer-ATnNt .framer-wxueil, .framer-ATnNt .framer-1uksdtr, .framer-ATnNt .framer-1aw1zwu { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-ATnNt .framer-yg1jta-container { flex: none; height: 40px; position: relative; width: auto; }",
	".framer-ATnNt .framer-1ug5mqs { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 10px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-ATnNt .framer-1he4jel-container { aspect-ratio: 1.7777777777777777 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 574px); position: relative; width: 1px; }",
	".framer-ATnNt .framer-2pn2o8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ATnNt .framer-1i4qadq, .framer-ATnNt .framer-1n3jcqh, .framer-ATnNt .framer-1rx4fuj { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-ATnNt.framer-v-15bd0no.framer-1hmdq4z { padding: 80px 32px 80px 32px; width: 810px; }",
	".framer-ATnNt.framer-v-15bd0no .framer-1he4jel-container, .framer-ATnNt.framer-v-109gjyv .framer-1he4jel-container { height: var(--framer-aspect-ratio-supported, 113px); }",
	".framer-ATnNt.framer-v-109gjyv.framer-1hmdq4z { padding: 80px 20px 80px 20px; width: 390px; }",
	".framer-ATnNt.framer-v-109gjyv .framer-2pn2o8 { flex-direction: column; }",
	".framer-ATnNt.framer-v-109gjyv .framer-1i4qadq, .framer-ATnNt.framer-v-109gjyv .framer-1n3jcqh, .framer-ATnNt.framer-v-109gjyv .framer-1rx4fuj { flex: none; width: 100%; }",
	...css,
	...css2,
	...css4,
	...css3,
	'.framer-ATnNt[data-border="true"]::after, .framer-ATnNt [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerOirQ4EhuU = withCSS(Component, css5, "framer-ATnNt");
var stdin_default3 = FramerOirQ4EhuU;
FramerOirQ4EhuU.displayName = "Video Section";
FramerOirQ4EhuU.defaultProps = {
	height: 1222,
	width: 1200,
};
addPropertyControls2(FramerOirQ4EhuU, {
	variant: {
		options: ["d9XwXt7BX", "HO0uYnuA6", "O29eogJzE"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType5.Enum,
	},
});
addFonts(
	FramerOirQ4EhuU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BadgeMiniFonts,
		...ButtonSecondaryFonts,
		...YouTubeFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:video-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "O29eogJzE",
	md: "HO0uYnuA6",
	xl: "d9XwXt7BX",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cfe7f02456486a1b782c98a22db14254d4e15a2a92102e54c71e84b8efc93bf4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var video_section_default = ComponentWithRoot;
export { video_section_default as default };
